/* Blave Agent — 報告 block 渲染器(從 web/app/static/js/agent/report_blocks.js 原樣搬進外殼;spec-desktop-0.1.6 §1.7)。
 * 搬運 delta 只有三處,其餘一字不改:
 *   ① BLOCKS.image 的參照 = sha256 || file(本機 drop dir 的 block 只有 file),交給 ctx.imageUrl(ref) 換成 data URI。
 *   ② makeCtx 多收 opts.markdown(md, ctx) → DocumentFragment|null:外殼沒有 marked / DOMPurify,text block 由呼叫端
 *      (renderer/reports.js 的 rptMarkdown,接 app.js 的 mdPaint)組節點;沒給才走 marked。
 *   ③ 中文字面(DIRECTION 的四個 key)改寫成跳脫碼:tests/check_shell_strings.js 不准 renderer 程式行出現中文字面。
 *
 *   renderAgentReport(container, report, opts) -> HTMLElement (the <article>)
 *
 * report = 契約 `.claude/docs/report-blocks.md` 的信封:
 *          { schema_version, id, type, title, created_at, blocks: [...] }
 *          ——產出資訊(origin / machine / generated_at)在首個 meta block 裡,
 *          不在信封。api 的 validate_report() 對未宣告的 prop 一律 400,所以這
 *          支渲染器只讀契約列出的欄位,不留別名分支。
 * opts   = { apiBase, i18n, imageUrl? }  ——apiBase/i18n 在 workspace.html 都是 IIFE
 *          內的區域變數,必須由呼叫端注入;缺了就退回檔內的 EN 預設(harness 用)。
 *          imageUrl(sha) 只有公開研究頁給(匿名圖片路徑)。
 *
 * 視覺 spec = designer `mockup-report-blocks.html` v1.2;樣式在
 * `css/agent/report.css`。圖表一律 SVG:mockup 的縮放語意(line/drawdown/bar
 * 拉伸、histogram/box/scatter 等比)本來就是 SVG 概念,而且 SVG 直接吃
 * var(--color-*),不必像 canvas 那樣快照 token,也沒有「面板 hidden 時
 * 容器寬度 0 畫不出來」那條既有陷阱。唯一例外是 candlestick:1px 影線與奇數
 * 寬實體要整數像素對齊才銳利,所以它量容器寬、1:1 繪製、寬度變了就重畫。
 *
 * SECURITY:報告內容全部來自使用者機器上的 agent = 不可信。文字一律
 * textContent、markdown 一律過 DOMPurify 白名單、圖片 src 只由 API base
 * 接上驗證過的 sha256。整份檔案沒有一處 innerHTML。
 */
(function (global) {
  "use strict";

  var SVG_NS = "http://www.w3.org/2000/svg";
  var MINUS = "−"; // U+2212,數字用的減號
  var DASH = "—"; // em dash = 缺值

  var DEFAULT_I18N = {
    originScheduled: "Generated by a scheduled task",
    originChat: "Generated from a conversation",
    machine: "Machine",
    footScheduled: "Generated on a schedule by the agent on your machine",
    footChat: "Generated from your conversation with the agent on your machine",
    metaPeriod: "Period",
    metaAum: "AUM",
    metaBenchmark: "Benchmark",
    calloutRisk: "Risk",
    imageError: "Image failed to load",
    footnoteRef: "Note",
    segOther: "Other",
  };

  // 帶 title/caption 的視覺 block(契約 §2)。meta/callout 的 title 是它們自己的
  // 東西(報告大標、提示卡標題),不能被這條通則渲染成區段小標
  var VISUAL = {
    kpi_row: 1, line_chart: 1, candlestick: 1, drawdown: 1, heatmap: 1, bar_chart: 1,
    histogram: 1, box: 1, scatter: 1, metric_table: 1, table: 1, code: 1,
    image: 1,
  };

  // ---------------------------------------------------------------- helpers
  function el(tag, cls, text) {
    var node = document.createElement(tag);
    if (cls) node.className = cls;
    if (text != null) node.textContent = text;
    return node;
  }

  function svgEl(tag, attrs) {
    var node = document.createElementNS(SVG_NS, tag);
    if (attrs) {
      Object.keys(attrs).forEach(function (k) {
        if (attrs[k] == null) return;
        node.setAttribute(k, String(attrs[k]));
      });
    }
    return node;
  }

  // 圖內文字也是值欄位:逐片段套同一組形狀集,SVG 裡由 tspan 承載 .mono
  // (text-anchor / font-size / fill 都由外層 text 供給,tspan 只換字體)
  function svgText(x, y, str_, attrs) {
    var node = svgEl("text", attrs || {});
    node.setAttribute("x", String(x));
    node.setAttribute("y", String(y));
    shapeRuns(str_).forEach(function (run) {
      if (!run.mono) {
        node.appendChild(document.createTextNode(run.t));
        return;
      }
      var span = svgEl("tspan", { class: "mono" });
      span.textContent = run.t;
      node.appendChild(span);
    });
    return node;
  }

  function num(v) {
    return typeof v === "number" && isFinite(v) ? v : null;
  }

  function str(v) {
    return typeof v === "string" ? v : v == null ? "" : String(v);
  }

  function arr(v) {
    return Array.isArray(v) ? v : [];
  }

  // 千分位。web 自己產的每個數字都走這裡:權益級的軸標與末值不分節會變成
  // 一串 24318.77(canon:數字要格式化)
  function group(s) {
    var parts = s.split(".");
    parts[0] = parts[0].replace(/\B(?=(\d{3})+$)/g, ",");
    return parts.join(".");
  }

  // 去掉小數尾零;負號一律 U+2212
  function trimNum(v, dp) {
    var s = Math.abs(v).toFixed(dp == null ? 2 : dp);
    if (s.indexOf(".") >= 0) s = s.replace(/0+$/, "").replace(/\.$/, "");
    return (v < 0 ? MINUS : "") + group(s);
  }

  function fmtSigned(v, dp) {
    if (v == null) return DASH;
    var s = group(Math.abs(v).toFixed(dp == null ? 2 : dp));
    return (v > 0 ? "+" : v < 0 ? MINUS : "") + s;
  }

  // meta.account.aum 是契約裡唯一要渲染器自己格式化的展示數字(其餘展示欄位
  // 都由產出端送已格式化字串)
  function fmtAmount(v) {
    return (v < 0 ? MINUS : "") + group(Math.abs(v).toFixed(2));
  }

  // 詞單位(次 / USDT / bp)與符號單位(% / × / ‰)的分界。詞單位只標一次
  // (縱軸左上、橫軸最右刻度之後),符號單位緊貼每個刻度——縱軸標籤區只有約
  // 32px,每個刻度重複一次「24,318 USDT」會壓進繪圖區(型錄「軸標共通規則」)
  function isWordUnit(unit) {
    return !!unit && /[A-Za-z0-9\u2e80-\u9fff]/.test(unit);
  }

  // 軸標。signed=座標含零或跨零(報酬類)時正值也標 +;純正值座標(波動、次數)
  // 不標,零刻度永遠是 0 不寫 +0。dp 由刻度步距決定(niceScale.dp):資金費率
  // 那種 0.005 步距的座標用固定兩位會把三條刻度全印成 0 / 0.01
  function fmtAxis(v, unit, signed, dp) {
    return (
      (signed && v > 0 ? "+" : "") +
      trimNum(v, dp == null ? 2 : dp) +
      (isWordUnit(unit) ? "" : unit || "")
    );
  }

  function fmtStamp(ts) {
    var d = new Date(ts * 1000);
    return (
      pad2(d.getMonth() + 1) +
      "/" +
      pad2(d.getDate()) +
      " " +
      pad2(d.getHours()) +
      ":" +
      pad2(d.getMinutes())
    );
  }

  function fmtDay(ts) {
    var d = new Date(ts * 1000);
    return pad2(d.getMonth() + 1) + "/" + pad2(d.getDate());
  }

  function fmtHM(ts) {
    var d = new Date(ts * 1000);
    return pad2(d.getHours()) + ":" + pad2(d.getMinutes());
  }

  function pad2(n) {
    return n < 10 ? "0" + n : String(n);
  }

  // 展示字串的正負語意:產出端送的是已格式化字串,符號就是唯一線索
  function signTone(text) {
    var c = text.charAt(0);
    if (c === "+") return " rb-up";
    if (c === MINUS || c === "-") return " rb-dn";
    return "";
  }

  // 一組 ~3 條格線的刻度
  function niceScale(min, max) {
    if (min == null || max == null || !isFinite(min) || !isFinite(max)) {
      min = 0;
      max = 1;
    }
    if (max === min) {
      max = min + Math.abs(min || 1) * 0.1;
    }
    var step = Math.pow(10, Math.floor(Math.log((max - min) / 3) / Math.LN10));
    var err = (max - min) / 3 / step;
    if (err >= 5) step *= 10;
    else if (err >= 2.5) step *= 5;
    else if (err >= 1.5) step *= 2;
    var lo = Math.floor(min / step) * step;
    var hi = Math.ceil(max / step) * step;
    var ticks = [];
    for (var i = 0; lo + step * i <= hi + step * 1e-6 && i < 20; i++) {
      var v = lo + step * i;
      ticks.push(Math.abs(v) < step * 1e-6 ? 0 : v);
    }
    // 刻度值印到步距那一位就夠(trimNum 再去尾零);floor 前減 1e-9 讓浮點誤差
    // 只會多印一位、不會少印
    var dp = Math.max(0, -Math.floor(Math.log(step) / Math.LN10 - 1e-9));
    return { lo: lo, hi: hi, ticks: ticks, dp: dp };
  }

  // ------------------------------------------------------- 中英混排 / 文字
  // 型錄收尾輪:自動包 .mono 只剩兩條路——值欄位與敘事欄位共用同一組
  // 封閉形狀集(monoShapes),標籤欄位不做句內自動包(monoLabel)。同一個
  // 字串落在哪個 JSON 欄位都長一樣:BTC 到哪裡都 mono、buy-hold 與
  // Sharpe 到哪裡都 sans。漢字絕不進 mono 是硬邊界。
  var HAS_CJK = /[\u2e80-\u9fff\uf900-\ufaff]/;

  // 封閉形狀集:含底線斜線等號冒號的識別字與賦值、全大寫 2–6 碼代號、數字量、
  // 日期時間。一般英文單字與混合大小寫術語(Sharpe / buy-hold)不包——會上錯
  // 標記的比對不做,只做安全退場的比對
  var SHAPE_RUN =
    /\d{4}-\d{2}-\d{2}|[A-Za-z0-9]+(?:[_/=:.][A-Za-z0-9]+)+[%×‰]?|[A-Z][A-Z0-9]{1,5}|[+−±-]?\d[\d,]*(?:\.\d+)?[%×‰]?/g;
  var WORD_CH = /[A-Za-z0-9_]/;
  // 兩個命中片段之間只隔這些字元時,連分隔符一起進 mono:型錄把
  // 「24,318.77 USDT」「08/25–08/31」當「整格就是一個數/代碼」處理,
  // 分隔符留在 sans 會在同一個值裡混出兩種字
  var JOINER = /^[\s\-–—−]+$/;
  var WHOLE_CODE = /^[A-Za-z0-9]+(?:[_/=:.-][A-Za-z0-9]+)*$/;

  // 形狀命中但左右仍黏著字母數字 = 它只是更長那個字的一段(七碼全大寫、
  // +0.88pp),那不是代碼
  function shapeRuns(text) {
    var runs = [];
    var last = 0;
    var m;
    SHAPE_RUN.lastIndex = 0;
    while ((m = SHAPE_RUN.exec(text))) {
      var end = m.index + m[0].length;
      var before = m.index > 0 ? text.charAt(m.index - 1) : "";
      var after = end < text.length ? text.charAt(end) : "";
      if (WORD_CH.test(before) || WORD_CH.test(after)) continue;
      if (m.index > last) runs.push({ t: text.slice(last, m.index), mono: false });
      runs.push({ t: m[0], mono: true });
      last = end;
    }
    if (last < text.length) runs.push({ t: text.slice(last), mono: false });
    for (var i = 1; i < runs.length - 1; i++) {
      if (
        !runs[i].mono &&
        runs[i - 1].mono &&
        runs[i + 1].mono &&
        JOINER.test(runs[i].t)
      ) {
        runs[i].mono = true;
      }
    }
    return runs;
  }

  // 整格就是一個識別字／代碼時整格 mono(blave-agent-01、eth_basis_carry)。
  // 連字號刻意不在片段形狀集裡(buy-hold 要留 sans),但整格是識別字時那個
  // 連字號就是識別字的一部分——沒有這條,blave-agent-01 只會包到尾巴的 01
  function isWholeCode(t) {
    return !!t && !HAS_CJK.test(t) && WHOLE_CODE.test(t) && /[_/=]|\d/.test(t);
  }

  function monoShapes(parent, text) {
    if (isWholeCode(text.trim())) {
      parent.appendChild(el("span", "mono", text));
      return parent;
    }
    shapeRuns(text).forEach(function (run) {
      parent.appendChild(
        run.mono ? el("span", "mono", run.t) : document.createTextNode(run.t)
      );
    });
    return parent;
  }

  // 標籤欄位(block title / kpi・metric・欄位 label):不做句內自動包——那裡的
  // 縮寫多半是術語詞組的一部分(「Max DD」「VaR(95%)」拆成半 sans 半 mono 更糟);
  // 只有整格本身就是識別字/代碼時整段 mono
  function monoLabel(parent, text) {
    if (isWholeCode(text.trim())) {
      parent.appendChild(el("span", "mono", text));
    } else {
      parent.appendChild(document.createTextNode(text));
    }
    return parent;
  }

  // ------------------------------------------------------- markdown 子集
  var MD_TAGS = [
    "p", "br", "strong", "em", "del", "ul", "ol", "li", "h2", "h3", "code", "a",
  ];

  var FN_REF = /\[\^([A-Za-z0-9_-]{1,32})\]/g;

  // CommonMark 的 flanking 規則:收尾的 ** 前面是標點、後面又直接接字時不算收尾
  // ——中文句子幾乎都長這樣(「…也拿得到?**做法是…」,正式 fixture 就有),marked
  // 會把星號原樣印出來。契約 §4 說 ** 就是粗體,所以成對的 ** 在進 marked 之前
  // 先換成 <strong>
  var STRONG_PAIR = /\*\*([^\s](?:[\s\S]*?[^\s])?)\*\*/g;
  var CODE_SPAN = /(```[\s\S]*?```|`+[^`]*`+)/;

  // 契約 §4:行內 code 與 fence 裡的東西一律原樣——`**kwargs` 不是粗體,
  // regex 範例 / pandas 索引裡的 `[^x]` 也不是尾註引用。兩個前置展開共用這套切法
  function outsideCode(md, fn) {
    return md
      .split(CODE_SPAN)
      .map(function (seg, i) {
        return i % 2 ? seg : fn(seg);
      })
      .join("");
  }

  // 契約 §4 的尾註引用。marked 沒有 footnote 語法,而契約又明文不支援 markdown
  // 連結,所以在餵給 marked 之前把 [^id] 換成錨點——不必自創 marked extension,
  // wire format 也只有 [^id] 一種。id 已由 api 驗過字元集,序號由本檔的 footnote
  // 對照表給(與尾註列表的序號同一份,任意 id 也對得起來)
  function expandFootnoteRefs(md, footnotes) {
    return outsideCode(md, function (seg) {
      return seg.replace(FN_REF, function (whole, id) {
        var n = footnotes[id];
        // 對不上的引用 api 會 400;真的漏進來就原樣留字面,不做出一個點不到的上標
        return n ? '<a href="#fn-' + id + '">' + n + "</a>" : whole;
      });
    });
  }

  function expandStrong(md) {
    return outsideCode(md, function (seg) {
      return seg.replace(STRONG_PAIR, "<strong>$1</strong>");
    });
  }

  // 上標跳到尾註列。這頁有 <base href> 指到站根,原生的 #fn-x 會被解析成
  // 另一個文件的 fragment(https://blave.org/#fn-x)——一般點擊會整頁導航走、
  // 聊天與面板狀態全丟,中鍵/Cmd 點擊則在新分頁開一個無關的首頁。上標只做
  // 「同頁跳到那條註解」一件事,所以三種點法一律在這裡收掉(修飾鍵走的還是
  // click 事件,preventDefault 就擋得住;中鍵走 auxclick,要另外接)。
  // id 已由 api 驗過字元集,但選擇器跳脫不值得賭:直接比對節點的 id
  function jumpToFootnote(e) {
    // 右鍵也會發 auxclick:context menu 是使用者自己叫的,不攔
    if (e.type === "auxclick" && e.button !== 1) return;
    e.preventDefault();
    var id = this.getAttribute("href").slice(1);
    var root = this.closest("article.rb-report");
    var target = null;
    if (root)
      Array.prototype.forEach.call(root.querySelectorAll(".rb-fn"), function (n) {
        if (!target && n.id === id) target = n;
      });
    if (!target) return;
    var reduce =
      global.matchMedia &&
      global.matchMedia("(prefers-reduced-motion: reduce)").matches;
    target.scrollIntoView({ behavior: reduce ? "auto" : "smooth", block: "center" });
    // 捲到了不等於讀螢幕的人也到了:非互動元素要先能被程式聚焦
    target.setAttribute("tabindex", "-1");
    target.focus({ preventScroll: true });
  }

  function mdFragment(md, ctx) {
    if (ctx.markdown) {
      var own = ctx.markdown(md, ctx);
      if (own) monoNarrative(own);
      return own;
    }
    if (!global.marked || !global.DOMPurify) return null;
    var frag = global.DOMPurify.sanitize(
      global.marked.parse(expandStrong(expandFootnoteRefs(md, ctx.footnotes))),
      {
        ALLOWED_TAGS: MD_TAGS,
        ALLOWED_ATTR: ["href"],
        RETURN_DOM_FRAGMENT: true,
      }
    );
    Array.prototype.forEach.call(frag.querySelectorAll("a"), function (a) {
      if ((a.getAttribute("href") || "").indexOf("#fn-") === 0) {
        a.className = "rb-fnref";
        a.setAttribute("aria-label", ctx.i18n.footnoteRef + " " + a.textContent);
        // workspace 的 DOMPurify 全域 hook 給每個 <a> 掛 target=_blank(聊天連結
        // 用);站內錨點被它帶走就變成開新分頁而不是跳到註解
        a.removeAttribute("target");
        a.removeAttribute("rel");
        // <base href> 陷阱,見 jumpToFootnote;中鍵不發 click,要另接 auxclick
        a.addEventListener("click", jumpToFootnote);
        a.addEventListener("auxclick", jumpToFootnote);
        return;
      }
      // 契約不支援連結:marked 從 [text](url) / autolink 生出來的 <a> 一律拆回純文字
      a.parentNode.replaceChild(document.createTextNode(a.textContent), a);
    });
    monoNarrative(frag);
    return frag;
  }

  // markdown 渲染完的樹走一遍 ②:code chip 與連結內不套用(已經是等寬,
  // 再包一次是雙重標記)
  function monoNarrative(root) {
    var walker = document.createTreeWalker(root, global.NodeFilter.SHOW_TEXT, null);
    var texts = [];
    var n;
    while ((n = walker.nextNode())) {
      var p = n.parentNode;
      var tag = p && p.nodeName;
      if (tag === "CODE" || tag === "A") continue;
      texts.push(n);
    }
    texts.forEach(function (node) {
      var frag = document.createDocumentFragment();
      monoShapes(frag, node.nodeValue);
      node.parentNode.replaceChild(frag, node);
    });
  }

  // ------------------------------------------------------------ Python 高亮
  var PY_KEYWORDS = {
    def: 1, class: 1, if: 1, elif: 1, else: 1, for: 1, while: 1, return: 1,
    import: 1, from: 1, as: 1, in: 1, not: 1, and: 1, or: 1, is: 1, None: 1,
    True: 1, False: 1, try: 1, except: 1, finally: 1, with: 1, lambda: 1,
    yield: 1, global: 1, pass: 1, break: 1, continue: 1, raise: 1, assert: 1,
    del: 1, async: 1, await: 1,
  };

  // 只上 keyword / string / number / comment 四類,其餘中性(canon Code syntax)
  function pyTokens(src) {
    var out = [];
    var i = 0;
    var plain = "";
    function flush() {
      if (plain) {
        out.push({ k: null, v: plain });
        plain = "";
      }
    }
    while (i < src.length) {
      var c = src.charAt(i);
      if (c === "#") {
        var end = src.indexOf("\n", i);
        if (end < 0) end = src.length;
        flush();
        out.push({ k: "c", v: src.slice(i, end) });
        i = end;
      } else if (c === '"' || c === "'") {
        var quote = src.substr(i, 3) === c + c + c ? c + c + c : c;
        var j = i + quote.length;
        while (j < src.length) {
          if (src.charAt(j) === "\\") {
            j += 2;
            continue;
          }
          if (src.substr(j, quote.length) === quote) {
            j += quote.length;
            break;
          }
          j++;
        }
        flush();
        out.push({ k: "s", v: src.slice(i, Math.min(j, src.length)) });
        i = j;
      } else if (/[0-9]/.test(c) && !/[A-Za-z_0-9]/.test(src.charAt(i - 1) || "")) {
        var k = i;
        while (k < src.length && /[0-9._eExXa-fA-F]/.test(src.charAt(k))) k++;
        flush();
        out.push({ k: "n", v: src.slice(i, k) });
        i = k;
      } else if (/[A-Za-z_]/.test(c)) {
        var w = i;
        while (w < src.length && /[A-Za-z_0-9]/.test(src.charAt(w))) w++;
        var word = src.slice(i, w);
        if (PY_KEYWORDS[word] === 1) {
          flush();
          out.push({ k: "k", v: word });
        } else {
          plain += word;
        }
        i = w;
      } else {
        plain += c;
        i++;
      }
    }
    flush();
    return out;
  }

  // ------------------------------------------------------------- SVG 圖表殼
  function chartSvg(b, w, h, stretch) {
    var s = svgEl("svg", {
      class: "rb-chart",
      viewBox: "0 0 " + w + " " + h,
      role: "img",
      "aria-label": str(b.title) || str(b.caption) || null,
    });
    // 折線/回撤沿用 mockup 的拉伸縮放;bar_chart bars 已是 1:1 像素,留著這個屬性只為讓
    // 看盤板 fitBlock 認得出要重畫的圖;histogram/box/scatter 不設此屬性
    // = 等比縮放,圓點與箱形不變形
    if (stretch) s.setAttribute("preserveAspectRatio", "none");
    return s;
  }

  // 拉伸類圖的畫布:呼叫端給了 chartSize 就用它,否則維持 mockup 的 680 × H
  function stretchSize(ctx, defH) {
    var cs = ctx && ctx.chartSize;
    return cs ? { W: cs.w, H: cs.h } : { W: 680, H: defH };
  }
  // 看盤板卡片縮到最小時 H 可能比軸標的固定內距還矮:繪圖區不得倒置,至少留 8
  function plotBottom(top, bottom) {
    return bottom - top < 8 ? Math.max(bottom, 8) : bottom;
  }
  function plotTopOf(top, bottom) {
    return bottom - top < 8 ? Math.max(0, bottom - 8) : top;
  }

  function watermark(s, x, y) {
    s.appendChild(
      svgText(x, y, "blave.org", { class: "rb-wm", "text-anchor": "end" })
    );
  }

  function gridLine(s, x1, y, x2) {
    s.appendChild(svgEl("line", { class: "rb-grid", x1: x1, y1: y, x2: x2, y2: y }));
  }

  // 圖內文字寬(viewBox 單位,字級 10px)。數字片段落在 tspan.mono(Roboto Mono
  // 字距 0.6em),漢字與全形標點(（）：／ 在 FF00–FFEF)1em;拉丁 sans 也按 0.6em 算,
  // 多數字母略寬於實際,但 W / M 這類大寫約 0.9em 會少估。
  // 不用 canvas 量:SVG 佈局只算一次,字型還沒載入時量到的是退場字型
  var FULL_WIDTH = /[\u2e80-\u9fff\uf900-\ufaff\uff00-\uffef]/;
  function textWidth(text) {
    var w = 0;
    for (var i = 0; i < text.length; i++) {
      w += FULL_WIDTH.test(text.charAt(i)) ? 10 : 6;
    }
    return w;
  }

  // 縱軸標籤區寬 = 繪圖區左界。最寬的刻度標(含詞單位那一行)決定它:五位數帶
  // 千分位是 36px,固定 36 的舊 gutter 只剩 30px 給標籤,45,000 會被 viewBox
  // 切成 5,000。標籤到格線 6px、到 viewBox 左緣 2px;窄標籤維持原本 36 不動
  function yGutter(scale, unit, signed) {
    if (signed == null) signed = scale.lo <= 0;
    var w = isWordUnit(unit) ? textWidth(unit) : 0;
    scale.ticks.forEach(function (t) {
      w = Math.max(w, textWidth(fmtAxis(t, unit, signed, scale.dp)));
    });
    return Math.max(36, 2 + w + 6);
  }

  // 左側 y 軸:格線 + 右對齊的軸標。單位一律由呼叫端給——契約的 y_unit / x_unit
  // 是純顯示後綴,沒帶就印裸數字;web 絕不自己猜一條序列是 % 還是 USDT。
  // 詞單位不逐刻度重複(fmtAxis 已擋),改標在頂刻度上方那一行、與刻度共用右界。
  // crisp = 1:1 像素繪製的圖(candlestick):1px 格線落在半像素才不糊成兩條淡線
  function yAxis(s, scale, top, bottom, padL, right, unit, signed, crisp) {
    if (signed == null) signed = scale.lo <= 0;
    var yAt = function (v) {
      return bottom - ((v - scale.lo) / (scale.hi - scale.lo)) * (bottom - top);
    };
    scale.ticks.forEach(function (t) {
      var y = crisp ? Math.round(yAt(t)) + 0.5 : yAt(t);
      gridLine(s, padL, y, right);
      s.appendChild(
        svgText(padL - 6, y + 3, fmtAxis(t, unit, signed, scale.dp), {
          "text-anchor": "end",
        })
      );
    });
    if (isWordUnit(unit)) {
      s.appendChild(svgText(padL - 6, top - 11, unit, { "text-anchor": "end" }));
    }
    return yAt;
  }

  // 詞單位在縱軸佔掉頂刻度上方那一行,繪圖區頂緣跟著下移(不下移會被 viewBox 切掉)
  function plotTop(top, unit) {
    return top + (isWordUnit(unit) ? 14 : 0);
  }

  // 橫軸的詞單位同樣只標一次,放最右刻度之後;寬度先從繪圖區右界扣掉,免得
  // 標籤被 viewBox 切掉
  function xUnitPad(unit) {
    return isWordUnit(unit) ? 8 + str(unit).length * 6 : 0;
  }

  function xUnitLabel(s, unit, right, y) {
    if (isWordUnit(unit)) {
      s.appendChild(svgText(right, y, unit, { "text-anchor": "end" }));
    }
  }

  function polyline(s, cls, pts) {
    s.appendChild(
      svgEl("polyline", {
        class: cls,
        points: pts
          .map(function (p) {
            return p[0].toFixed(1) + "," + p[1].toFixed(1);
          })
          .join(" "),
      })
    );
  }

  // ------------------------------------------------------------------ blocks
  var BLOCKS = {};

  BLOCKS.meta = function (b, ctx) {
    var head = el("header", "rb-meta");
    var title = str(b.title);
    var h1 = el("h1", "rb-title");
    monoShapes(h1, title);
    // 標題已含類型時不重複渲染 tag(型錄:週報標題自帶「績效週報」→ 無 tag)
    var rtype = str(b.report_type);
    if (rtype && title.indexOf(rtype) < 0) {
      h1.appendChild(el("span", "rb-type-tag", rtype));
    }
    head.appendChild(h1);

    // 產出資訊行:時間戳與機器名是值(整格 mono),產出方式與「機器」是敘述
    var line = el("div", "rb-meta-line");
    var sep = function () {
      if (line.childNodes.length) line.appendChild(document.createTextNode(" · "));
    };
    if (b.origin) {
      sep();
      line.appendChild(
        document.createTextNode(
          b.origin === "scheduled" ? ctx.i18n.originScheduled : ctx.i18n.originChat
        )
      );
    }
    var stamp = num(b.generated_at);
    if (stamp != null) {
      sep();
      monoShapes(line, fmtStamp(stamp));
    }
    if (b.machine) {
      sep();
      line.appendChild(document.createTextNode(ctx.i18n.machine + " "));
      monoShapes(line, str(b.machine));
    }
    if (line.childNodes.length) head.appendChild(line);

    var cells = [];
    if (b.period) {
      cells.push([
        ctx.i18n.metaPeriod,
        str(b.period.from) + "–" + str(b.period.to),
      ]);
    }
    if (b.account) {
      var aum = num(b.account.aum);
      cells.push([
        ctx.i18n.metaAum,
        (aum == null ? DASH : fmtAmount(aum)) + " " + str(b.account.currency),
      ]);
    }
    if (b.benchmark) cells.push([ctx.i18n.metaBenchmark, str(b.benchmark)]);
    arr(b.extra).forEach(function (it) {
      if (it) cells.push([str(it.label), str(it.value)]);
    });

    if (cells.length) {
      var strip = el("div", "rb-strip");
      cells.forEach(function (pair) {
        var cell = el("div", "rb-strip-cell");
        cell.appendChild(el("div", "rb-strip-label", pair[0]));
        var val = el("div", "rb-strip-value");
        monoShapes(val, pair[1]);
        cell.appendChild(val);
        strip.appendChild(cell);
      });
      head.appendChild(strip);
    }
    return head;
  };

  BLOCKS.kpi_row = function (b) {
    var items = arr(b.items);
    if (!items.length) return null;
    var hasDelta = items.some(function (it) {
      return it && it.delta;
    });
    // 格數進 class:一行最多 5 格,6 格(契約上限)固定折成 3+3 等寬網格,
    // 不放任自由 wrap 折出 5+1 孤兒
    var row = el(
      "div",
      "rb-kpi is-n" + items.length + (hasDelta ? " has-delta" : "")
    );
    items.forEach(function (it, i) {
      var cell = el("div", "rb-kpi-cell" + (i === 0 ? " is-focus" : ""));
      cell.appendChild(monoLabel(el("div", "rb-kpi-label"), str(it.label)));
      var tone = it.tone === "pos" ? " rb-up" : it.tone === "neg" ? " rb-dn" : "";
      var val = el("div", "rb-kpi-value" + tone);
      monoShapes(val, str(it.value));
      // unit 是值的度量,貼在值後同一行;不吃 tone 色(語意色只屬於數字)
      if (it.unit) val.appendChild(monoShapes(el("span", "rb-kpi-unit"), str(it.unit)));
      cell.appendChild(val);
      // delta 是另一件事(值=現況、delta=變化)→ 另起第三行、不上漲跌色。列內
      // 任一格有 delta 就全列補這一行,否則底對齊會把缺席那格的值往下拉
      if (hasDelta) {
        var d = el("div", "rb-kpi-delta");
        if (it.delta) monoShapes(d, str(it.delta));
        cell.appendChild(d);
      }
      row.appendChild(cell);
    });
    return row;
  };

  BLOCKS.line_chart = function (b, ctx) {
    var series = arr(b.series).filter(function (s) {
      return arr(s.points).length > 1;
    });
    if (!series.length) return null;

    var sz = stretchSize(ctx, 210);
    var W = sz.W, H = sz.H, right = W - 8, bottom = H - 44;
    var yUnit = str(b.y_unit);
    var top = plotTop(24, yUnit);
    bottom = plotBottom(top, bottom);
    top = plotTopOf(top, bottom);

    var tLo = Infinity, tHi = -Infinity, maxIdx = 0;
    var vLo = Infinity, vHi = -Infinity;
    series.forEach(function (s) {
      var pts = arr(s.points);
      maxIdx = Math.max(maxIdx, pts.length - 1);
      pts.forEach(function (p) {
        tLo = Math.min(tLo, p[0]);
        tHi = Math.max(tHi, p[0]);
        vLo = Math.min(vLo, p[1]);
        vHi = Math.max(vHi, p[1]);
      });
    });
    // 真實時間軸:採樣不等距才畫得對,band 的起訖也才有得對照。整段同一個
    // 時間戳(單日多序列)退回等距,避免除以零
    var spread = tHi > tLo;
    var xOfT = function (t) {
      return x0 + ((t - tLo) / (tHi - tLo)) * (x1 - x0);
    };
    var xAt = function (p, i) {
      if (spread) return xOfT(p[0]);
      return x0 + (maxIdx ? (i / maxIdx) * (x1 - x0) : 0);
    };

    arr(b.reflines).forEach(function (r) {
      vLo = Math.min(vLo, r.y);
      vHi = Math.max(vHi, r.y);
    });
    var scale = niceScale(vLo, vHi);
    var padL = yGutter(scale, yUnit);
    var x0 = padL + 4, x1 = W - 20;
    var s = chartSvg(b, W, H, true);
    // 浮水印是背景 furniture:最先繪(最底層)、落點固定繪圖區右下,被資料
    // 蓋過去是允許的(型錄裁示 5——層序問題,不是位置問題)
    watermark(s, W - 12, bottom - 12);

    // 區間底紋在格線之下:標的是「什麼時候」,中性色調提升、不借語意色
    if (spread) {
      arr(b.bands).forEach(function (band) {
        var bx = xOfT(Math.max(band.from, tLo));
        var bw = xOfT(Math.min(band.to, tHi)) - bx;
        s.appendChild(
          svgEl("rect", {
            class: "rb-band",
            x: bx,
            y: top,
            width: Math.max(0, bw),
            height: bottom - top,
          })
        );
        if (band.label) s.appendChild(svgText(bx + 8, top + 12, str(band.label)));
      });
    }

    var yAt = yAxis(s, scale, top, bottom, padL, right, yUnit);

    // benchmark 先畫,主序列壓在上面
    series
      .slice()
      .sort(function (a, z) {
        return (a.role === "primary" ? 1 : 0) - (z.role === "primary" ? 1 : 0);
      })
      .forEach(function (sr) {
        var pts = arr(sr.points).map(function (p, i) {
          return [xAt(p, i), yAt(p[1])];
        });
        polyline(s, sr.role === "benchmark" ? "rb-s2" : "rb-s1", pts);
      });

    arr(b.reflines).forEach(function (r) {
      var y = yAt(r.y);
      var em = r.emphasis ? " is-em" : "";
      s.appendChild(
        svgEl("line", { class: "rb-ref" + em, x1: padL, y1: y, x2: right, y2: y })
      );
      s.appendChild(
        svgText(right - 4, y - 4, str(r.label), {
          class: "rb-ref-label" + em,
          "text-anchor": "end",
        })
      );
    });

    // x 軸:頭 / 兩個中段 / 尾
    var base = arr(series[0].points);
    [0, 1, 2, 3].forEach(function (k) {
      var i = Math.round(((base.length - 1) * k) / 3);
      var p = base[i];
      if (!p) return;
      s.appendChild(
        svgText(xAt(p, i), H - 10, fmtDay(p[0]), {
          "text-anchor": k === 0 ? "start" : k === 3 ? "end" : "middle",
        })
      );
    });

    var wrap = el("div");
    wrap.appendChild(s);
    var legend = el("div", "rb-legend");
    series.forEach(function (sr) {
      var item = el("span");
      item.appendChild(
        el("span", "rb-legend-sw" + (sr.role === "benchmark" ? " is-dash" : ""))
      );
      monoShapes(item, str(sr.name));
      var pts = arr(sr.points);
      var last = pts[pts.length - 1];
      if (last) {
        item.appendChild(
          el(
            "span",
            "rb-legend-val mono",
            fmtSigned(last[1], 2) + (isWordUnit(yUnit) ? " " : "") + yUnit
          )
        );
      }
      legend.appendChild(item);
    });
    wrap.appendChild(legend);
    return wrap;
  };

  // 型錄 #cat-candlestick。x 軸是「一根一格」的位置軸(契約 §3):不留假日/收盤
  // 空白,所以刻意不與相鄰 line_chart 的真實時間軸對齊
  BLOCKS.candlestick = function (b, ctx) {
    // 與 api 驗證同一條:l ≤ min(o,c) ≤ max(o,c) ≤ h。壞 K 棒丟掉,不讓一根
    // 反轉的高低點把整張圖的縱軸撐爆
    var candles = arr(b.candles).filter(function (k) {
      return (
        Array.isArray(k) &&
        k.length === 5 &&
        k.every(function (v) {
          return num(v) !== null;
        }) &&
        k[3] <= Math.min(k[1], k[4]) &&
        Math.max(k[1], k[4]) <= k[2]
      );
    });
    if (candles.length < 2) return null;

    var wrap = el("div");
    var svg = null;
    var drawnW = 0;
    function draw(W, H) {
      W = Math.round(W);
      if (W < 80 || W === drawnW) return;
      drawnW = W;
      var next = candleSvg(b, candles, W, H);
      if (svg) wrap.replaceChild(next, svg);
      else wrap.appendChild(next);
      svg = next;
    }

    if (ctx.chartSize) {
      draw(ctx.chartSize.w, ctx.chartSize.h);
      return wrap;
    }
    if (typeof global.ResizeObserver !== "function") {
      draw(680, 210);
      return wrap;
    }
    // 報告建好才掛上 DOM,建的當下量不到寬:交給共用的寬度觀測,面板從 hidden
    // 變可見、拖寬度時也靠它重畫。量的是零高的尺(只隨寬度變)
    if (!ctx.swept) {
      sweepDetached();
      ctx.swept = true;
    }
    var ruler = el("div");
    wrap.appendChild(ruler);
    watchWidth(ruler, function (w) {
      draw(w, 210);
    });
    return wrap;
  };

  // candlestick / bar_chart bars 的寬度觀測:全模組共用一個 ResizeObserver,host → draw。工作頁是
  // 長壽 SPA,每張圖各開一個 observer 又沒斷乾淨就是每開一份報告漏一個
  var widthHosts = new Map();
  var widthPending = new Map();
  var widthRO = null;
  var widthFrame = 0;

  function watchWidth(host, draw) {
    if (!widthRO) widthRO = new global.ResizeObserver(onWidth);
    widthHosts.set(host, { draw: draw, seen: false });
    widthRO.observe(host);
  }

  function releaseWidth(host) {
    widthRO.unobserve(host);
    widthHosts.delete(host);
    widthPending.delete(host);
  }

  // 被拔出 document 的 host:掛上過的會在拔出時以 0 寬觸發 onWidth 當場釋放;
  // 從沒掛上過、或掛在 hidden 面板裡就被清空的,尺寸一直是 0、不會再觸發,靠下一
  // 次渲染 candlestick 前的這一掃。所以殘留上限是一份報告,不會累積
  function sweepDetached() {
    widthHosts.forEach(function (rec, host) {
      if (!host.isConnected) releaseWidth(host);
    });
  }

  // 重畫延到下一幀:畫完可能讓捲軸出現、改到同一幀觀測中的寬度,在 callback
  // 裡直接畫會觸發 ResizeObserver loop 錯誤。同一幀多次 resize 只畫最後一次。
  // 不在 document 但從沒掛上過 = 報告建好、還沒被放進頁面(首次觀測就長這樣),
  // 這時釋放就再也畫不出來,留給 sweepDetached
  function onWidth(entries) {
    entries.forEach(function (e) {
      var rec = widthHosts.get(e.target);
      if (!rec) return;
      if (!e.target.isConnected) {
        if (rec.seen) releaseWidth(e.target);
        return;
      }
      rec.seen = true;
      widthPending.set(e.target, e.contentRect.width);
    });
    if (widthPending.size && !widthFrame) {
      widthFrame = global.requestAnimationFrame(flushWidth);
    }
  }

  function flushWidth() {
    widthFrame = 0;
    var pending = widthPending;
    widthPending = new Map();
    pending.forEach(function (w, host) {
      var rec = widthHosts.get(host);
      if (rec && host.isConnected) rec.draw(w);
    });
  }

  // 不超過 slot × 0.75 的最大奇數,夾在 [1, 13]:奇數才讓 1px 影線落在實體正中
  // 那一格;slot < 4 時自然退成 1px,整根降階成有色高低線
  function candleBody(slot) {
    var n = Math.floor(slot * 0.75);
    if (n % 2 === 0) n -= 1;
    return Math.min(13, Math.max(1, n));
  }

  function candleSvg(b, candles, W, H) {
    var right = W - 8;
    var yUnit = str(b.y_unit);
    var top = plotTop(24, yUnit);
    var bottom = plotBottom(top, H - 44);
    top = plotTopOf(top, bottom);

    var refs = arr(b.reflines).filter(function (r) {
      return r && num(r.y) !== null;
    });
    var lo = Infinity, hi = -Infinity;
    candles.forEach(function (k) {
      lo = Math.min(lo, k[3]);
      hi = Math.max(hi, k[2]);
    });
    refs.forEach(function (r) {
      lo = Math.min(lo, r.y);
      hi = Math.max(hi, r.y);
    });
    var scale = niceScale(lo, hi);
    // 價格軸恆不帶 +(跨零的價差也一樣),不吃 lo <= 0 的預設判斷
    var padL = yGutter(scale, yUnit, false);
    var x0 = padL + 4, x1 = W - 8;
    var slot = (x1 - x0) / candles.length;
    var body = candleBody(slot);
    var cxOf = function (i) {
      return Math.floor(x0 + (i + 0.5) * slot) + 0.5;
    };

    var s = chartSvg(b, W, H, false);
    watermark(s, W - 12, bottom - 12);
    var yAt = yAxis(s, scale, top, bottom, padL, right, yUnit, false, true);
    var yPx = function (v) {
      return Math.round(yAt(v));
    };

    // 參考線在 K 棒之下、標籤在之上:線被蓋一段不影響讀,標籤被蓋就讀不到
    var refY = refs.map(function (r) {
      // 1px 虛線落半像素、2px 實線(emphasis)落整數像素,兩種都不糊
      var y = yPx(r.y) + (r.emphasis ? 0 : 0.5);
      s.appendChild(
        svgEl("line", {
          class: "rb-ref" + (r.emphasis ? " is-em" : ""),
          x1: padL,
          y1: y,
          x2: right,
          y2: y,
        })
      );
      return y;
    });

    var g = svgEl("g", { "shape-rendering": "crispEdges" });
    candles.forEach(function (k, i) {
      var cls = k[4] >= k[1] ? "rb-bar-up" : "rb-bar-dn"; // 收平算漲
      var cx = cxOf(i);
      var yh = yPx(k[2]), yl = yPx(k[3]);
      g.appendChild(
        svgEl("rect", { class: cls, x: cx - 0.5, y: yh, width: 1, height: Math.max(1, yl - yh) })
      );
      var yt = yPx(Math.max(k[1], k[4])), yb = yPx(Math.min(k[1], k[4]));
      g.appendChild(
        svgEl("rect", {
          class: cls,
          x: cx - body / 2,
          y: yt,
          width: body,
          height: Math.max(1, yb - yt),
        })
      );
    });
    s.appendChild(g);

    // 標籤放左端:20 日高/低這類水位按定義是最近那段 K 棒碰出來的,放右端必壓在
    // 最新幾根上
    refs.forEach(function (r, i) {
      s.appendChild(
        svgText(x0 + 4, refY[i] - 4, str(r.label), {
          class: "rb-ref-label" + (r.emphasis ? " is-em" : ""),
        })
      );
    });

    candleTicks(
      candles.map(function (k) {
        return k[0];
      }),
      cxOf,
      W
    ).forEach(function (t) {
      s.appendChild(svgText(t.x, H - 10, t.text, { "text-anchor": t.anchor }));
    });
    return s;
  }

  // 位置軸刻度:落在週期邊界,刻度本身就是分段(「八月從這裡開始」)。優先序
  // 最後一根 → 邊界由右往左 → 第一根;與已放的標籤距離 < 12px 或同字就丟。
  // 時間走瀏覽器本地時區,同 line_chart 的軸標
  function candleTicks(ts, cxOf, W) {
    var n = ts.length;
    var diffs = [];
    for (var i = 1; i < n; i++) diffs.push(ts[i] - ts[i - 1]);
    diffs.sort(function (a, z) {
      return a - z;
    });
    var dayKey = function (t) {
      var d = new Date(t * 1000);
      return d.getFullYear() + "-" + d.getMonth() + "-" + d.getDate();
    };
    var key, fmt;
    // 間距中位數 ≥ 20h = 日 K 以上(跳假日不影響中位數)
    if (diffs[Math.floor(diffs.length / 2)] >= 20 * 3600) {
      fmt = fmtDay;
      key =
        ts[n - 1] - ts[0] > 56 * 86400
          ? function (t) {
              var d = new Date(t * 1000);
              return d.getFullYear() + "-" + d.getMonth();
            }
          : function (t) {
              var d = new Date(t * 1000);
              d.setHours(0, 0, 0, 0);
              d.setDate(d.getDate() - ((d.getDay() + 6) % 7)); // 週一起算
              return d.getTime();
            };
    } else if (dayKey(ts[0]) !== dayKey(ts[n - 1])) {
      fmt = fmtDay;
      key = dayKey;
    } else {
      fmt = fmtHM;
      key = function (t) {
        return new Date(t * 1000).getHours();
      };
    }

    var order = [n - 1];
    for (var j = n - 1; j >= 1; j--) {
      if (key(ts[j]) !== key(ts[j - 1])) order.push(j);
    }
    order.push(0);

    var kept = [];
    order.forEach(function (idx) {
      var text = fmt(ts[idx]);
      if (kept.some(function (k) { return k.text === text; })) return;
      var cx = cxOf(idx), w = textWidth(text);
      var l = cx - w / 2, r = cx + w / 2, x = cx, anchor = "middle";
      if (l < 2) {
        l = 2;
        r = 2 + w;
        x = 2;
        anchor = "start";
      }
      if (r > W - 2) {
        r = W - 2;
        l = r - w;
        x = r;
        anchor = "end";
      }
      if (kept.some(function (k) { return l < k.r + 12 && r > k.l - 12; })) return;
      kept.push({ text: text, l: l, r: r, x: x, anchor: anchor });
    });
    return kept;
  }

  BLOCKS.drawdown = function (b, ctx) {
    var pts = arr(b.points);
    if (pts.length < 2) return null;

    var sz = stretchSize(ctx, 130);
    var W = sz.W, H = sz.H, right = W - 8, top = 15, bottom = plotBottom(15, H - 25);
    top = plotTopOf(top, bottom);
    var vals = pts.map(function (p) {
      return p[1];
    });
    var scale = niceScale(
      Math.min.apply(null, vals),
      Math.max.apply(null, vals.concat([0]))
    );
    var padL = yGutter(scale, "%");
    var x0 = padL + 4, x1 = W - 20;
    var s = chartSvg(b, W, H, true);
    watermark(s, W - 12, bottom - 8);
    // 回撤是契約唯一釘死單位的座標(負值百分比),故不吃 y_unit
    var yAt = yAxis(s, scale, top, bottom, padL, right, "%");

    var xAt = function (i) {
      return x0 + (i / (pts.length - 1)) * (x1 - x0);
    };
    var line = pts.map(function (p, i) {
      return [xAt(i), yAt(p[1])];
    });
    var zero = yAt(Math.min(scale.hi, Math.max(scale.lo, 0)));
    var d =
      "M" +
      line
        .map(function (p) {
          return p[0].toFixed(1) + "," + p[1].toFixed(1);
        })
        .join(" L") +
      " L" + line[line.length - 1][0].toFixed(1) + "," + zero.toFixed(1) +
      " L" + line[0][0].toFixed(1) + "," + zero.toFixed(1) + " Z";
    s.appendChild(svgEl("path", { class: "rb-dd-area", d: d }));
    polyline(s, "rb-dd-line", line);

    // 最深回撤註記(值+日期)。maxdd.to = 谷底時點,對到最近的取樣點才畫得準
    var worst = 0;
    vals.forEach(function (v, i) {
      if (v < vals[worst]) worst = i;
    });
    var md = b.maxdd;
    if (md) {
      pts.forEach(function (p, i) {
        if (Math.abs(p[0] - md.to) < Math.abs(pts[worst][0] - md.to)) worst = i;
      });
    }
    var note =
      fmtSigned(md ? md.value : vals[worst], 2) + "%" + " · " + fmtDay(pts[worst][0]);
    s.appendChild(
      svgText(xAt(worst), bottom + 15, note, {
        class: "rb-dd-note",
        "text-anchor": "middle",
      })
    );

    var wrap = el("div");
    wrap.appendChild(s);
    return wrap;
  };

  // 色深四階,|值| 分級;正負由符號承載,色只做強度。門檻由變體決定
  // (calendar=月報酬 %、matrix=相關係數),契約不帶門檻欄位
  var HEAT_STEPS = { calendar: [1, 2.5, 4.5], matrix: [0.25, 0.5, 0.75] };

  function heatClass(v, steps) {
    var a = Math.abs(v);
    var step = a < steps[0] ? 1 : a < steps[1] ? 2 : a < steps[2] ? 3 : 4;
    return (v < 0 ? "rb-r" : "rb-g") + step;
  }

  BLOCKS.heatmap = function (b) {
    var matrix = b.variant === "matrix";
    var labels = arr(b.labels);
    var rows = matrix ? labels : arr(b.rows);
    var cols = matrix ? labels : arr(b.cols);
    var values = arr(b.values);
    if (!rows.length || !cols.length) return null;
    var steps = HEAT_STEPS[matrix ? "matrix" : "calendar"];
    // calendar 限定:標示「年度/總計」這種要加重的欄。用索引而不是「最後一欄
    // 就是總計」的慣例——cols 是純字串,web 認不出哪一欄是總計
    var emph = {};
    if (!matrix) {
      arr(b.emphasis_cols).forEach(function (i) {
        if (typeof i === "number") emph[i] = 1;
      });
    }

    var wrap = el("div", "rb-heat-wrap");
    var table = el("table", "rb-heat");
    if (b.title || b.caption) {
      table.setAttribute("aria-label", str(b.title) || str(b.caption));
    }
    var thead = el("thead");
    var htr = el("tr");
    htr.appendChild(el("th", "rb-heat-row"));
    cols.forEach(function (c, ci) {
      // 方陣的欄標籤走序號:窄欄塞不下長策略名,對應靠列標籤前面的同一個序號
      htr.appendChild(monoShapes(el("th"), matrix ? String(ci + 1) : str(c)));
    });
    thead.appendChild(htr);
    table.appendChild(thead);

    var tbody = el("tbody");
    rows.forEach(function (r, ri) {
      var tr = el("tr");
      var th = el("th", "rb-heat-row");
      th.setAttribute("scope", "row");
      monoShapes(th, matrix ? ri + 1 + " " + str(r) : str(r));
      tr.appendChild(th);
      cols.forEach(function (c, ci) {
        var v = num(arr(values[ri])[ci]);
        var em = emph[ci] ? " is-em" : "";
        // null = 未到月份 / 對角線自相關,無資訊 → em-dash 無底色
        tr.appendChild(
          v == null
            ? el("td", "is-na" + em, DASH)
            : el("td", heatClass(v, steps) + em, fmtSigned(v, 2))
        );
      });
      tbody.appendChild(tr);
    });
    table.appendChild(tbody);
    wrap.appendChild(table);
    return wrap;
  };

  BLOCKS.bar_chart = function (b, ctx) {
    return b.variant === "stacked" ? stackedBar(b, ctx) : signedBars(b, ctx);
  };

  // bars 兩個方向都以 1:1 真像素繪製:固定 680 viewBox 等比縮放時格寬與字寬同比縮,
  // 手機和桌機量出來一樣,方向規則就判斷不了。報告頁走 candlestick 的量寬路徑,
  // 看盤板用 chartSize(內縮 16 只給橫條:直條維持貼齊三緣)
  function signedBars(b, ctx) {
    // 值只收真數字:字串數字會讓 Math.max / 縮放算出來的柱高錯位(api 已驗型別,
    // 這是與檔內其他 block 一致的防禦深度)
    var items = arr(b.items).filter(function (it) {
      return it && num(it.value) !== null;
    });
    if (!items.length) return null;
    var vals = items.map(function (it) {
      return it.value;
    });
    var d = {
      rows: items.map(function (it) {
        return { name: str(it.label), v: it.value, val: fmtSigned(it.value, 2) };
      }),
      maxPos: Math.max(0, Math.max.apply(null, vals)),
      maxNeg: Math.max(0, -Math.min.apply(null, vals)),
    };
    var inset = ctx.chartSize ? 16 : 0;

    var wrap = el("div");
    var svg = null;
    var drawnW = 0;
    function draw(W, H) {
      W = Math.round(W);
      if (W < 80 || W === drawnW) return;
      drawnW = W;
      // 方向只看寬度;報告頁捲軸出現/消失不改寬度,靠捲動容器的 scrollbar-gutter: stable
      var upright = barsUpright(d.rows, W);
      var next = upright ? verticalBars(b, d, W, H) : horizontalBars(b, d, W, inset);
      wrap.classList.toggle("rb-hwrap", !upright);
      if (svg) wrap.replaceChild(next, svg);
      else wrap.appendChild(next);
      svg = next;
    }

    if (ctx.chartSize) {
      draw(ctx.chartSize.w, ctx.chartSize.h);
      return wrap;
    }
    if (typeof global.ResizeObserver !== "function") {
      draw(680, 170);
      // 量不到寬:橫條照 680 × 自然高畫、交給 width:100% 等比縮放,不能帶著釘死的高被橫向擠扁
      if (svg.classList.contains("rb-hbars")) {
        svg.removeAttribute("preserveAspectRatio");
        svg.removeAttribute("height");
      }
      return wrap;
    }
    if (!ctx.swept) {
      sweepDetached();
      ctx.swept = true;
    }
    var ruler = el("div");
    wrap.appendChild(ruler);
    watchWidth(ruler, function (w) {
      draw(w, 170);
    });
    return wrap;
  }

  // 每一項的名稱與值標都原樣放得進 W / N 的格寬才用直條(+4 = 相鄰標籤最少空隙);
  // 類別標籤不能像時間軸那樣抽稀或旋轉,放不下就整張改橫條,同一張圖不混用
  function barsUpright(rows, W) {
    var slot = W / rows.length;
    return rows.every(function (r) {
      return Math.max(textWidth(r.name), textWidth(r.val)) + 4 <= slot;
    });
  }

  function verticalBars(b, d, W, H) {
    var top = 24, bottom = plotBottom(24, H - 52), nameY = H - 18;
    top = plotTopOf(top, bottom);
    var span = d.maxPos + d.maxNeg || 1;
    var zeroY = top + ((bottom - top) * d.maxPos) / span;

    var s = chartSvg(b, W, H, true);
    // bars 變體不給浮水印例外(型錄裁示 5):同樣最底層繪、落點固定右下
    watermark(s, W - 8, bottom - 7);
    s.appendChild(svgEl("line", { class: "rb-grid", x1: 0, y1: zeroY, x2: W, y2: zeroY }));

    var slot = W / d.rows.length;
    var barW = Math.min(64, slot * 0.45);
    d.rows.forEach(function (r, i) {
      var cx = slot * (i + 0.5);
      var h = (Math.abs(r.v) / span) * (bottom - top);
      var up = r.v >= 0;
      s.appendChild(
        svgEl("rect", {
          class: up ? "rb-bar-up" : "rb-bar-dn",
          x: cx - barW / 2,
          y: up ? zeroY - h : zeroY,
          width: barW,
          height: Math.max(1, h),
        })
      );
      s.appendChild(
        svgText(cx, up ? zeroY - h - 8 : zeroY + h + 15, r.val, {
          class: up ? "rb-val-up" : "rb-val-dn",
          "text-anchor": "middle",
        })
      );
      s.appendChild(svgText(cx, nameY, r.name, { "text-anchor": "middle" }));
    });
    return s;
  }

  // 橫條:高度只由 N 決定、與寬度無關——看盤板靠這點在門檻附近不來回跳
  function horizontalBars(b, d, W, inset) {
    var PITCH = 20, TOP = 4;
    var n = d.rows.length;
    var plotB = TOP + PITCH * n;
    var H = plotB + (inset ? 16 : 4);
    var cap = Math.min(160, Math.floor(0.3 * (W - 2 * inset)));
    var nameW = 0, negW = 0, posW = 0;
    d.rows.forEach(function (r) {
      nameW = Math.max(nameW, textWidth(r.name));
      var w = textWidth(r.val) + 4;
      if (r.v < 0) negW = Math.max(negW, w);
      else posW = Math.max(posW, w);
    });
    nameW = Math.min(nameW, cap);
    // 兩側先預留各自最長值標的欄寬,最長的負值標籤也碰不到名稱欄
    var barX0 = inset + nameW + 8 + negW;
    var plotW = Math.max(0, W - inset - posW - barX0);
    var span = d.maxPos + d.maxNeg || 1;
    var zeroX = Math.round(barX0 + (plotW * d.maxNeg) / span);

    var s = chartSvg(b, W, H, true);
    // 高度要釘住:.rb-chart 只給 width:100%,留給 viewBox 比例推高度的話,寬一變高就跟著
    // 縮放,看盤板 fitBlock 量到的就不是自己畫的高
    s.setAttribute("height", String(H));
    s.classList.add("rb-hbars");
    watermark(s, W - inset - 8, plotB - 7);
    // 全負值時零軸落在右緣 W(報告頁 inset 0),1px 線再往右半格就整條出畫布,夾回最後一格
    var axisX = Math.min(zeroX, W - 1) + 0.5;
    s.appendChild(svgEl("line", { class: "rb-grid", x1: axisX, y1: TOP, x2: axisX, y2: plotB }));

    d.rows.forEach(function (r, i) {
      var rowTop = TOP + PITCH * i;
      var len = Math.max(1, (Math.abs(r.v) / span) * plotW);
      var up = r.v >= 0;
      var name = clipText(r.name, nameW);
      var host = s;
      if (name !== r.name) {
        host = svgEl("g");
        var tip = svgEl("title");
        tip.textContent = r.name;
        host.appendChild(tip);
        s.appendChild(host);
      }
      host.appendChild(
        svgEl("rect", {
          class: up ? "rb-bar-up" : "rb-bar-dn",
          x: up ? zeroX : zeroX - len,
          y: rowTop + 4,
          width: len,
          height: 12,
        })
      );
      host.appendChild(
        svgText(up ? zeroX + len + 4 : zeroX - len - 4, rowTop + 13, r.val, {
          class: up ? "rb-val-up" : "rb-val-dn",
          "text-anchor": up ? "start" : "end",
        })
      );
      host.appendChild(svgText(inset, rowTop + 13, name, { "text-anchor": "start" }));
    });
    return s;
  }

  // 截到「已累加寬 + … 的 6」不超過 maxW;按 code point 走,不把代理對切成兩半
  function clipText(text, maxW) {
    if (textWidth(text) <= maxW) return text;
    var out = "", w = 0;
    var chars = Array.from(text);
    for (var i = 0; i < chars.length; i++) {
      var cw = textWidth(chars[i]);
      if (w + cw + 6 > maxW) break;
      out += chars[i];
      w += cw;
    }
    return out + "…";
  }

  // 配色分流看維度、不看段數:恰兩段且兩段 label 都命中封閉方向對 → 多空語意色;
  // 其餘一律類別色(BTC/ETH 兩段條上 green/red 會謊稱「一邊在賺一邊在賠」)
  var DIRECTION = {
    "\u591a": "up", "\u7a7a": "dn", "\u505a\u591a": "up", "\u505a\u7a7a": "dn",
    long: "up", short: "dn",
  };

  function duoTone(segs) {
    if (segs.length !== 2) return null;
    var a = DIRECTION[str(segs[0].label).trim().toLowerCase()];
    var z = DIRECTION[str(segs[1].label).trim().toLowerCase()];
    return a && z && a !== z ? [a, z] : null;
  }

  function stackedBar(b, ctx) {
    // 同 signedBars:字串數字放行的話 reduce 會變字串串接,寬度百分比整條歪掉
    var segs = arr(b.segments).filter(function (sg) {
      return sg && num(sg.value) > 0;
    });
    if (!segs.length) return null;
    var duo = duoTone(segs);
    var rows;
    if (duo) {
      rows = segs.map(function (sg, i) {
        return { label: str(sg.label), value: sg.value, kind: "is-" + duo[i] };
      });
    } else {
      // 類別構成比:依值由大到小排序後走 data-1~4,第 5 段起併成一段灰色——
      // canon 只有四個類別色,循環會出現兩段同色、讀者分不出哪段是哪段。契約
      // 已把 segments 收成 2–4,這條是越界 payload 的保底
      var sorted = segs.slice().sort(function (a, z) {
        return z.value - a.value;
      });
      rows = sorted.slice(0, 4).map(function (sg, i) {
        return { label: str(sg.label), value: sg.value, kind: "is-d" + (i + 1) };
      });
      var rest = sorted.slice(4);
      if (rest.length) {
        rows.push({
          label: rest.length === 1 ? str(rest[0].label) : ctx.i18n.segOther,
          value: rest.reduce(function (a, sg) {
            return a + sg.value;
          }, 0),
          kind: "is-rest",
        });
      }
    }
    var total = rows.reduce(function (a, r) {
      return a + r.value;
    }, 0);
    var wrap = el("div", "rb-exposure");
    var bar = el("div", "rb-bar");
    var legend = el("div", "rb-legend");
    rows.forEach(function (r) {
      var pct = (r.value / total) * 100;
      var seg = el("span", "rb-bar-seg " + r.kind);
      seg.style.width = pct.toFixed(2) + "%";
      bar.appendChild(seg);
      // 條內一律不放文字,名稱與值都在下方 legend
      var item = el("span");
      item.appendChild(el("span", "rb-sw2 " + r.kind));
      monoShapes(item, r.label);
      item.appendChild(el("span", "rb-legend-val mono", pct.toFixed(0) + "%"));
      legend.appendChild(item);
    });
    wrap.appendChild(bar);
    wrap.appendChild(legend);
    return wrap;
  }

  BLOCKS.histogram = function (b) {
    var bins = arr(b.bins);
    if (!bins.length) return null;
    var W = 680, H = 225, right = 672, bottom = 185;
    var yUnit = str(b.y_unit);
    var xUnit = str(b.x_unit);
    var top = plotTop(15, yUnit);
    var lo = bins[0].x0, hi = bins[bins.length - 1].x1;
    arr(b.reflines).forEach(function (r) {
      lo = Math.min(lo, r.x);
      hi = Math.max(hi, r.x);
    });
    var maxCount = Math.max.apply(
      null,
      bins.map(function (bin) {
        return bin.count;
      })
    );
    var scale = niceScale(0, maxCount);
    var padL = yGutter(scale, yUnit, false);
    var x0 = padL + 4, x1 = 660 - xUnitPad(xUnit);
    var s = chartSvg(b, W, H, false);
    watermark(s, 668, bottom - 7);
    // 縱軸是次數(契約:count ≥ 0 整數)→ 恆不帶正負號
    var yAt = yAxis(s, scale, top, bottom, padL, right, yUnit, false);
    var xAt = function (v) {
      return x0 + ((v - lo) / (hi - lo || 1)) * (x1 - x0);
    };

    // 單一分布 = 一個序列 → 全 data-1;不用漲跌色
    bins.forEach(function (bin) {
      var bx = xAt(bin.x0);
      var bw = Math.max(1, xAt(bin.x1) - bx - 2); // bin 間 2px 縫
      var h = (bin.count / (scale.hi || 1)) * (bottom - top);
      s.appendChild(
        svgEl("rect", {
          class: "rb-hist-bar",
          x: bx,
          y: bottom - h,
          width: bw,
          height: Math.max(0, h),
        })
      );
    });

    arr(b.reflines).forEach(function (r) {
      var x = xAt(r.x);
      var em = r.emphasis ? " is-em" : "";
      s.appendChild(
        svgEl("line", { class: "rb-ref" + em, x1: x, y1: top, x2: x, y2: bottom })
      );
      s.appendChild(
        svgText(x, top - 5, str(r.label), {
          class: "rb-ref-label" + em,
          "text-anchor": "middle",
        })
      );
    });

    var xScale = niceScale(lo, hi);
    xScale.ticks.forEach(function (v) {
      if (v < lo || v > hi) return;
      var label = fmtAxis(v, xUnit, xScale.lo <= 0, xScale.dp);
      var x = xAt(v), half = textWidth(label) / 2;
      // 置中的刻度標在繪圖區兩端會伸出 viewBox:貼邊的改成靠邊對齊
      s.appendChild(
        svgText(x, 205, label, {
          "text-anchor": x + half > W ? "end" : x - half < 0 ? "start" : "middle",
        })
      );
    });
    xUnitLabel(s, xUnit, right, 205);

    var wrap = el("div");
    wrap.appendChild(s);
    return wrap;
  };

  BLOCKS.box = function (b) {
    var groups = arr(b.groups);
    if (!groups.length) return null;
    var W = 680, H = 215, right = 672, bottom = 180, labelY = 205;
    var yUnit = str(b.y_unit);
    var top = plotTop(25, yUnit);
    var lo = Infinity, hi = -Infinity;
    groups.forEach(function (g) {
      lo = Math.min(lo, g.min);
      hi = Math.max(hi, g.max);
      arr(g.outliers).forEach(function (o) {
        lo = Math.min(lo, o);
        hi = Math.max(hi, o);
      });
    });
    var scale = niceScale(lo, hi);
    var padL = yGutter(scale, yUnit);
    var x0 = padL + 4, x1 = 660;
    var s = chartSvg(b, W, H, false);
    watermark(s, 668, bottom - 7);
    // 橫軸是分組類別(groups[].label),契約因此只有 y_unit
    var yAt = yAxis(s, scale, top, bottom, padL, right, yUnit);

    var slot = (x1 - x0) / groups.length;
    var boxW = Math.min(64, slot * 0.45);
    var capW = Math.min(24, boxW * 0.4);
    // 全組同色 data-1:分組是同一變數的參數切片,不是類別序列
    groups.forEach(function (g, i) {
      var cx = x0 + slot * (i + 0.5);
      var q1 = yAt(g.q1), q3 = yAt(g.q3), med = yAt(g.median);
      var yHigh = yAt(g.max), yLow = yAt(g.min);
      s.appendChild(svgEl("line", { class: "rb-box", x1: cx, y1: yHigh, x2: cx, y2: q3 }));
      s.appendChild(
        svgEl("line", { class: "rb-box", x1: cx - capW, y1: yHigh, x2: cx + capW, y2: yHigh })
      );
      s.appendChild(svgEl("line", { class: "rb-box", x1: cx, y1: q1, x2: cx, y2: yLow }));
      s.appendChild(
        svgEl("line", { class: "rb-box", x1: cx - capW, y1: yLow, x2: cx + capW, y2: yLow })
      );
      s.appendChild(
        svgEl("rect", {
          class: "rb-box",
          x: cx - boxW / 2,
          y: Math.min(q1, q3),
          width: boxW,
          height: Math.max(1, Math.abs(q1 - q3)),
        })
      );
      s.appendChild(
        svgEl("line", { class: "rb-box-med", x1: cx - boxW / 2, y1: med, x2: cx + boxW / 2, y2: med })
      );
      // 單筆觀測的視覺重量必須低於「箱」這個匯總圖形:空心 r2.5、描線比箱體
      // 細一階;不填色、不 jitter、不加標籤
      arr(g.outliers).forEach(function (o) {
        s.appendChild(svgEl("circle", { class: "rb-out", cx: cx, cy: yAt(o), r: 2.5 }));
      });
      s.appendChild(svgText(cx, labelY, str(g.label), { "text-anchor": "middle" }));
    });

    var wrap = el("div");
    wrap.appendChild(s);
    return wrap;
  };

  BLOCKS.scatter = function (b) {
    var pts = arr(b.points);
    if (!pts.length) return null;
    var W = 680, H = 240, right = 672, bottom = 190, xLabelY = 210;
    var yUnit = str(b.y_unit);
    var xUnit = str(b.x_unit);
    var top = plotTop(15, yUnit);
    var xs = pts.map(function (p) {
      return p.x;
    });
    var ys = pts.map(function (p) {
      return p.y;
    });
    var xScale = niceScale(Math.min.apply(null, xs), Math.max.apply(null, xs));
    var yScale = niceScale(Math.min.apply(null, ys), Math.max.apply(null, ys));
    var padL = yGutter(yScale, yUnit);
    var x0 = padL, x1 = 660 - xUnitPad(xUnit);
    var s = chartSvg(b, W, H, false);
    watermark(s, 668, bottom - 7);
    var yAt = yAxis(s, yScale, top, bottom, padL, right, yUnit);
    var xAt = function (v) {
      return x0 + ((v - xScale.lo) / (xScale.hi - xScale.lo || 1)) * (x1 - x0);
    };

    // 回歸線是衍生註記、不是第二序列 → 註記線家族預設樣式
    var reg = b.regression;
    if (reg) {
      var a = reg.slope, c = reg.intercept;
      // 裁到繪圖區內:回歸線延伸到 y 範圍外會畫進軸標區
      var ends = [xScale.lo, xScale.hi].map(function (x) {
        var y = a * x + c;
        if (a !== 0 && y < yScale.lo) return [(yScale.lo - c) / a, yScale.lo];
        if (a !== 0 && y > yScale.hi) return [(yScale.hi - c) / a, yScale.hi];
        return [x, Math.min(yScale.hi, Math.max(yScale.lo, y))];
      });
      if (ends[1][0] > ends[0][0]) {
        s.appendChild(
          svgEl("line", {
            class: "rb-ref",
            x1: xAt(ends[0][0]),
            y1: yAt(ends[0][1]),
            x2: xAt(ends[1][0]),
            y2: yAt(ends[1][1]),
          })
        );
      }
    }

    // 全部省略 role = 單一母體,全點 data-1
    var twoClass = pts.some(function (p) {
      return p.role === "focus" || p.role === "context";
    });
    pts.forEach(function (p) {
      var focus = twoClass && p.role === "focus";
      var px = xAt(p.x), py = yAt(p.y);
      s.appendChild(
        svgEl("circle", {
          class: focus || !twoClass ? "rb-pt1" : "rb-pt2",
          cx: px,
          cy: py,
          r: focus ? 6 : 5,
        })
      );
      if (!p.label) return;
      // 標籤直接放點旁(五個點的圖用 legend 是繞路)。焦點點一律往左放(mockup
      // 做法,把右側留給 context 點的標籤);其餘看落在左右哪半邊
      var left = focus || px > x0 + (x1 - x0) * 0.6;
      var ly = py < top + 14 ? py + 14 : py - 6; // 貼上緣的點,標籤改放下方
      s.appendChild(
        svgText(px + (left ? -12 : 12), ly, str(p.label), {
          class: "rb-pt-label" + (focus ? " is-focus" : ""),
          "text-anchor": left ? "end" : "start",
        })
      );
    });

    [0, 1, 2].forEach(function (k) {
      var v = xScale.lo + ((xScale.hi - xScale.lo) * k) / 2;
      s.appendChild(
        svgText(xAt(v), xLabelY, fmtAxis(v, xUnit, xScale.lo <= 0, xScale.dp), {
          "text-anchor": k === 0 ? "start" : k === 2 ? "end" : "middle",
        })
      );
    });
    xUnitLabel(s, xUnit, right, xLabelY);

    var wrap = el("div");
    wrap.appendChild(s);
    return wrap;
  };

  BLOCKS.metric_table = function (b) {
    var items = arr(b.items);
    if (!items.length) return null;
    var grid = el("div", "rb-metrics");
    items.forEach(function (it) {
      var row = el("div", "rb-metric-row");
      row.appendChild(monoLabel(el("span", "rb-metric-label"), str(it.label)));
      var value = str(it.value);
      // format 是漲跌語意色的閘門(與 table.columns[].format 同一條):只有
      // number / percent 上色,text(預設)/ date 一律中性——敞口的 + 是方向、
      // 不是損益,塗綠就是說謊
      var toned = it.format === "number" || it.format === "percent";
      var val = el("span", "rb-metric-value" + (toned ? signTone(value) : ""));
      monoShapes(val, value);
      row.appendChild(val);
      grid.appendChild(row);
    });
    return grid;
  };

  BLOCKS.table = function (b) {
    var cols = arr(b.columns);
    var rows = arr(b.rows);
    if (!cols.length) return null;
    var wrap = el("div", "rb-table-wrap");
    var table = el("table", "rb-table");
    var thead = el("thead");
    var htr = el("tr");
    cols.forEach(function (c) {
      htr.appendChild(monoLabel(el("th", alignClass(c.align)), str(c.label)));
    });
    thead.appendChild(htr);
    table.appendChild(thead);
    var tbody = el("tbody");
    rows.forEach(function (r) {
      var tr = el("tr");
      cols.forEach(function (c) {
        var cell = r ? r[c.key] : null;
        var text = cell == null ? "" : typeof cell === "number" ? String(cell) : cell;
        // format 是漲跌語意色的閘門:只有 number / percent 的欄套用,text / date
        // 一律不上色(契約 §3 table)
        var toned = c.format === "number" || c.format === "percent";
        var td = el("td", (alignClass(c.align) + (toned ? signTone(text) : "")).trim());
        if (text === "") td.textContent = DASH;
        else monoShapes(td, text);
        tr.appendChild(td);
      });
      tbody.appendChild(tr);
    });
    table.appendChild(tbody);
    wrap.appendChild(table);
    return wrap;
  };

  function alignClass(align) {
    return align === "right" ? "rb-num" : align === "center" ? "rb-mid" : "";
  }

  BLOCKS.text = function (b, ctx) {
    var md = str(b.markdown);
    if (!md) return null;
    var wrap = el("div", "rb-text" + (b.variant === "lead" ? " rb-lead" : ""));
    var frag = mdFragment(md, ctx);
    if (frag) {
      wrap.appendChild(frag);
    } else {
      // marked/DOMPurify 沒載到:退回純文字段落,永不 innerHTML
      md.split(/\n{2,}/).forEach(function (para) {
        wrap.appendChild(el("p", null, para));
      });
    }
    return wrap;
  };

  BLOCKS.quote = function (b) {
    var text = str(b.text);
    if (!text) return null;
    var wrap = monoShapes(el("blockquote", "rb-quote"), text);
    // cite 是內容的一部分(歸屬),與引文共用左界內縮;不加破折號、不加引號
    if (b.cite) {
      wrap.appendChild(monoShapes(el("div", "rb-quote-cite"), str(b.cite)));
    }
    return wrap;
  };

  BLOCKS.footnote = function (b, ctx) {
    var items = arr(b.items);
    if (!items.length) return null;
    var wrap = el("div", "rb-footnotes");
    items.forEach(function (it, i) {
      var row = el("div", "rb-fn");
      row.id = "fn-" + str(it.id);
      // 序號用位次而非 id:內文上標與這裡必須是同一組號,而 id 可以是任意字串
      row.appendChild(el("span", "rb-fn-no mono", String(i + 1)));
      row.appendChild(monoShapes(el("span"), str(it.text)));
      row.setAttribute("aria-label", ctx.i18n.footnoteRef + " " + (i + 1));
      wrap.appendChild(row);
    });
    return wrap;
  };

  BLOCKS.code = function (b) {
    var source = str(b.source);
    if (!source) return null;
    var wrap = el("div", "rb-code");
    var pre = el("pre");
    if (str(b.lang).toLowerCase() === "python") {
      pyTokens(source).forEach(function (t) {
        // 每個 token 都是獨立的 textContent 節點——原始碼裡的 <script> 只會
        // 當字面文字渲染
        pre.appendChild(t.k ? el("span", "rb-tok-" + t.k, t.v) : document.createTextNode(t.v));
      });
    } else {
      pre.textContent = source;
    }
    wrap.appendChild(pre);
    return wrap;
  };

  BLOCKS.divider = function () {
    return el("hr", "rb-divider");
  };

  BLOCKS.callout = function (b, ctx) {
    var info = b.tone === "info";
    var wrap = el("div", "rb-callout" + (info ? " is-info" : ""));
    var title = str(b.title);
    if (title) {
      var head = el("div", "rb-callout-title");
      monoShapes(head, title);
      // 嚴重度由 tag 文字承載,標題不用紅字(red 對 darkCard 過不了內文 AA)
      if (!info) head.appendChild(el("span", "rb-callout-tag", ctx.i18n.calloutRisk));
      wrap.appendChild(head);
    }
    wrap.appendChild(monoShapes(el("div", "rb-callout-body"), str(b.text)));
    return wrap;
  };

  BLOCKS.image = function (b, ctx) {
    // 平台上的圖是 sha256;本機 drop dir 的圖是 file(sidecar 檔名,report-blocks.md §2.5)。兩個都沒有 = 沒圖可畫
    var sha = str(b.sha256);
    var ref = sha || str(b.file);
    if (!ref) return null;
    var wrap = el("div", "rb-image");
    var img = document.createElement("img");
    img.alt = str(b.alt); // 契約必填,不給預設值
    // 讀取時 api 補的 w/h:先佔位才不會每張圖載入後撐開、在讀者眼前跳版。走
    // 屬性而不是 aspect-ratio,才會同時保住「小圖不放大」(max-width + height:auto)。
    // 兩個欄位可能整組缺席(量不出檔頭/舊圖),缺席就退回載入後撐開
    var iw = num(b.w);
    var ih = num(b.h);
    if (iw > 0 && ih > 0) {
      img.width = iw;
      img.height = ih;
    }
    // 破圖 icon 留在報告裡比沒有更糟:就地換成一格失敗說明,內容是 alt——alt 才
    // 是使用者要的資訊(這張圖本來要說什麼)。不放 Retry:整頁重載即重試,而圖
    // 以 sha256 定址,取不到多半是真的不在了。listener 必須先掛再設 src,否則
    // 命中快取的失敗會在掛上去之前就發生
    img.addEventListener("error", function () {
      var fail = el("div", "rb-image-fail");
      fail.appendChild(el("div", "rb-image-fail-l", ctx.i18n.imageError));
      if (img.alt) fail.appendChild(el("div", "rb-image-fail-alt", img.alt));
      if (img.parentNode) img.parentNode.replaceChild(fail, img);
    });
    img.src = ctx.imageUrl
      ? ctx.imageUrl(ref)
      : /^[0-9a-f]{64}$/.test(sha) ? ctx.apiBase + "openclaw/agent/strategy_image/" + sha : "";
    wrap.appendChild(img);
    return wrap;
  };

  // divider 的用途是「換幕但不立小標」,判準因此是下一幕有沒有自己的開場:
  // 緊鄰小標(block 的 title / markdown H2 / H3)、報告頭尾、meta 之後、
  // footnote 之前(它自帶頂線)、連續 divider 第二條起,一律省略
  function dividerRedundant(blocks, i) {
    function isHeadingEdge(b, tail) {
      if (!b) return true; // 報告頭尾的 divider 也不留
      // 連續 divider 只砍後面那些,第一條留著(它才是那個「換幕」)
      if (b.type === "divider") return tail;
      if (b.type === "meta") return tail; // 報告頭:meta 自帶 label:value 列
      if (b.type === "footnote") return !tail; // 尾註自帶頂線
      if (VISUAL[b.type] && b.title) return !tail;
      if (b.type !== "text") return false;
      var lines = str(b.markdown).split("\n").filter(function (l) {
        return l.trim() !== "";
      });
      return /^#{2,3}\s/.test(str(tail ? lines[lines.length - 1] : lines[0]));
    }
    return isHeadingEdge(blocks[i - 1], true) || isHeadingEdge(blocks[i + 1], false);
  }

  // ------------------------------------------------------------------ 入口
  function makeCtx(opts, report) {
    opts = opts || {};
    var apiBase = str(opts.apiBase);
    if (apiBase && apiBase.charAt(apiBase.length - 1) !== "/") apiBase += "/";
    var i18n = {};
    Object.keys(DEFAULT_I18N).forEach(function (k) {
      i18n[k] = (opts.i18n && opts.i18n[k]) || DEFAULT_I18N[k];
    });
    // chartSize:拉伸類圖(line_chart / drawdown / bar_chart)與 candlestick 的 viewBox
    // 尺寸。報告頁不給 = line_chart / drawdown 固定 680 寬、candlestick 與 bar_chart
    // bars 自己量容器;看盤板 block 量
    // 卡片內容區後給 1:1 像素,文字才不會被 preserveAspectRatio:none 拉變形
    // (watchboard.md §3.2)
    var size = opts.chartSize && typeof opts.chartSize === "object" ? opts.chartSize : null;
    var chartSize =
      size && num(size.w) >= 80 && num(size.h) >= 16
        ? { w: Math.round(size.w), h: Math.round(size.h) }
        : null;
    // imageUrl(sha):公開頁的圖走匿名路徑(report-sharing §3),不給 = 登入的 strategy_image
    var imageUrl = typeof opts.imageUrl === "function" ? opts.imageUrl : null;
    // markdown(md, ctx):呼叫端自己的 markdown → DOM(外殼);不給就走 marked + DOMPurify
    var markdown = typeof opts.markdown === "function" ? opts.markdown : null;
    return {
      apiBase: apiBase,
      i18n: i18n,
      report: report || {},
      footnotes: {},
      chartSize: chartSize,
      imageUrl: imageUrl,
      markdown: markdown,
    };
  }

  // 單顆 block 的渲染(工作頁回測分頁的 MCPT 分佈圖借 histogram 幾何用):只回
  // 該 block 的 DOM,不帶 .rb-block wrapper / 小標 / caption;呼叫端要放進
  // .rb-report 範圍內 report.css 的 .rb-chart 家族才生效。不認得或畫失敗 → null
  function renderReportBlock(block, opts) {
    var fn =
      block && typeof block === "object" && Object.prototype.hasOwnProperty.call(BLOCKS, block.type)
        ? BLOCKS[block.type]
        : null;
    if (!fn) return null;
    try {
      return fn(block, makeCtx(opts));
    } catch (e) {
      if (global.console) console.warn("[report] block failed:", block.type, e);
      return null;
    }
  }

  function renderAgentReport(container, report, opts) {
    var ctx = makeCtx(opts, report);

    var article = el("article", "rb-report");
    var blocks = arr(ctx.report.blocks);

    // 內文的 [^id] 上標要在渲染 text block 之前就知道每個 id 的位次,而 footnote
    // block 依契約在最後
    blocks.forEach(function (b) {
      if (!b || b.type !== "footnote") return;
      arr(b.items).forEach(function (it, i) {
        if (it && typeof it.id === "string") ctx.footnotes[it.id] = i + 1;
      });
    });

    blocks.forEach(function (b, i) {
      if (!b || typeof b !== "object") return;
      var fn = Object.prototype.hasOwnProperty.call(BLOCKS, b.type) ? BLOCKS[b.type] : null;
      if (!fn) {
        // 契約升版會帶新 block type,舊的 web 還在跑:不認得就跳過,
        // 一顆看不懂的 block 不該讓整份報告消失
        if (global.console) console.warn("[report] unknown block type:", b.type);
        return;
      }
      if (b.type === "divider" && dividerRedundant(blocks, i)) return;
      var node = null;
      try {
        node = fn(b, ctx);
      } catch (e) {
        if (global.console) console.warn("[report] block failed:", b.type, e);
        return;
      }
      if (!node) return;
      var wrap = el("div", "rb-block");
      if (VISUAL[b.type] && b.title) {
        wrap.appendChild(monoLabel(el("h2", "rb-h"), str(b.title)));
      }
      wrap.appendChild(node);
      if (VISUAL[b.type] && b.caption) {
        wrap.appendChild(monoShapes(el("div", "rb-cap"), str(b.caption)));
      }
      article.appendChild(wrap);
    });

    var foot = reportFoot(blocks[0], ctx);
    if (foot) article.appendChild(foot);

    if (container) {
      container.textContent = "";
      container.appendChild(article);
    }
    return article;
  }

  // 報告尾的產出說明列——不是 block 之一,由 meta.origin 推;時間與機器名已在
  // 報告頭那行,這裡只講「這份東西是你自己機器上的 agent 產的」
  function reportFoot(meta, ctx) {
    if (!meta || meta.type !== "meta" || !meta.origin) return null;
    return el(
      "div",
      "rb-foot",
      meta.origin === "scheduled" ? ctx.i18n.footScheduled : ctx.i18n.footChat
    );
  }

  global.renderAgentReport = renderAgentReport;
  global.renderReportBlock = renderReportBlock;
})(window);
