/* GENERATED from shell/i18n/*.po by shell/tools/po2js.py — do not edit by hand.
 *
 * Add or change a string in the `.po` files, then re-run the generator and
 * commit both. The runtime helpers (t / setLang / pickLang) are NOT here —
 * they live in renderer/i18n.js, which this file never overwrites.
 */
const STRINGS = {
  en: {
    "cn.h": "Blave has no AI of its own.",
    "cn.blave.title": "Use Blave's AI",
    "cn.blave.desc": "First card adds 100 TWD of AI credit, then pay per use",
    "cn.blave.btn": "Sign in to Blave",
    "cn.blave.switch": "Switch",
    "cn.local.label": "Local agent",
    "cn.local.desc": "Your Claude Code or Codex — no Blave AI fee",
    "cn.redetect": "Detect again",
    "cn.detecting": "Detecting…",
    "cn.connect": "Connect",
    "cn.foot": "You can switch at any time.",
    "st.signedIn": "Signed in",
    "st.notSignedIn": "Not signed in",
    "st.notFound": "Not found",
    "oauth.waiting": "Waiting for the browser…",
    "oauth.cancel": "Cancel",
    "oauth.opened": "The authorization page is open in your browser. You'll come back here automatically.",
    "oauth.failed": "Authorization failed.",
    "OAUTH_CANCELLED": "Cancelled. Press the button again to use Blave's AI.",
    "OAUTH_TIMEOUT": "Authorization timed out (5 minutes).",
    "OAUTH_STATE_MISMATCH": "The reply didn't match this request and was rejected.",
    "OAUTH_NO_CODE": "The browser came back without an authorization code.",
    "OAUTH_DENIED": "You cancelled the authorization in the browser.",
    "KEYCHAIN_UNAVAILABLE": "This computer can't store credentials securely (Keychain unavailable), so nothing was saved.",
    "TOKEN_EXCHANGE_FAILED": "Could not exchange the authorization code for a token.",
    "ws.chatExample": "Backtest a BTC 20/50 moving-average strategy",
    "ws.strategies": "Strategies",
    "ws.noStrategies": "No strategies yet.",
    "ws.placeholder": "Message the agent",
    "ws.send": "Send",
    "ws.settings": "Settings",
    "turn.process": "Thought process",
    "turn.thinking": "Thinking",
    "turn.running": "Running · step {n}",
    "turn.busy": "The previous turn is still running.",
    "turn.engineFailed": "Engine setup failed: {msg}",
    "turn.exit": "Engine exited with code {code}",
    "turn.error": "Something went wrong: {msg}",
    "fault.authInvalid": "This computer’s Blave sign-in is no longer valid, so this turn didn’t run.",
    "fault.authBtn": "Sign In Again",
    "fault.noCredit": "Your Blave balance is empty, so this turn didn’t run.",
    "fault.noCreditBtn": "Top Up",
    "conn.expired": "Your Blave sign-in is no longer valid. Sign in again to continue.",
    "engine.workspace": "Creating the workspace at ~/Blave/workspace …",
    "engine.deps": "Installing the Python packages strategies need (pandas, numpy…), first run only…",
    "engine.preparing": "Preparing the engine (first run installs it, about a minute)…",
    "mp.model": "Model",
    "mp.effort": "Effort",
    "mp.default": "Default",
    "mp.aria": "Model and effort: {model}, {effort}",
    "mp.ariaNoEffort": "Model: {model}",
    "mp.cap": "Default for {model}: {level}. Higher thinks longer and uses more.",
    "mp.none": "This model has no effort setting.",
    "lv.low": "Low",
    "lv.medium": "Medium",
    "lv.high": "High",
    "lv.xhigh": "Extra High",
    "lv.max": "Max",
    "lv.ultra": "Ultra",
    "fault.noModel": "Your account can't use {model}. This turn did not run.",
    "fault.noModelSwitched": "Your account can't use {model}. This turn did not run — switched back to {to}.",
    "fault.noModelBtn": "Choose a Model",
    "mp.na": "Not on your plan",
    "rp.tab.backtest": "Backtest",
    "rp.tab.trades": "Trades",
    "rp.tab.code": "Code",
    "bt.fee": "fee",
    "bt.totalReturn": "Total Return",
    "bt.benchmark": "Benchmark",
    "bt.benchmarkRank": "Beat {n}% of random portfolios",
    "bt.sharpe": "Sharpe",
    "bt.maxDrawdown": "Max Drawdown",
    "bt.trades": "Trades",
    "bt.mcpt": "MCPT p-value",
    "bt.mcptTipSig": "Shuffled {n} times; only {pct} of the shuffles beat it. Below 0.05 is the usual bar.",
    "bt.mcptTipNs": "Shuffled {n} times; {pct} of the shuffles beat it — above the usual 0.05 bar, so this result can't be told apart from luck.",
    "bt.equity": "Equity",
    "bt.drawdown": "Drawdown",
    "bt.chartAria": "Equity curve and drawdown over the backtest period",
    "bt.monthly": "Monthly returns",
    "bt.year": "Year",
    "bt.empty": "No backtest data for this strategy.",
    "tr.empty": "This strategy has no entries or exits.",
    "tr.chartError": "Couldn't draw the chart. The entries and exits below are still available.",
    "tr.list": "Entries & exits",
    "tr.count": "{n} trades",
    "tr.buy": "Buy",
    "tr.sell": "Sell",
    "tr.kind.open": "Open",
    "tr.kind.close": "Close",
    "tr.kind.flip": "Flip",
    "tr.position": "Position {n}",
    "bt.grpReturns": "Returns",
    "bt.grpRisk": "Risk",
    "bt.grpTrading": "Trading",
    "bt.annReturn": "Annualized Return",
    "bt.annVol": "Annualized Vol",
    "bt.sortino": "Sortino",
    "bt.omega": "Omega",
    "bt.winRate": "Daily Win Rate",
    "bt.totalFees": "Total Fees",
    "bt.mcptDistTitle": "MCPT · Sharpe across {n} shuffles, p = {p}",
    "bt.mcptDistActual": "Actual Sharpe {v}",
    "bt.mcptDistUnit": "shuffles",
    "ws.resizeSide": "Resize strategy list",
    "ws.resizeChat": "Resize chat",
    "ws.sideCollapse": "Collapse strategy list",
    "ws.sideExpand": "Expand strategy list",
    "ws.chatCollapse": "Collapse chat",
    "ws.chatExpand": "Expand chat",
    "set.close": "Close",
    "set.cats": "Settings categories",
    "set.cat.display": "Display",
    "set.cat.model": "Model access",
    "set.lang": "Language",
    "cn.current": "In use",
    "cs.all": "All chats",
    "cs.back": "Back to chat",
    "cs.new": "New chat",
    "cs.del": "Delete chat",
    "cs.delConfirm": "Delete?",
    "strat.del": "Move to Trash",
    "bt.tip.totalReturn": "Cumulative return over the whole backtest, net of fees.",
    "bt.tip.annReturn": "Total return converted to a compounded yearly rate, so backtests of different lengths can be compared.",
    "bt.tip.benchmark": "What buying and holding this symbol over the same period would have returned. The strategy has to beat it to be better than doing nothing.",
    "bt.tip.benchmarkRank": "Share of randomly picked buy-and-hold portfolios that this strategy’s total return beats.",
    "bt.tip.annVol": "Standard deviation of daily returns, scaled to a year. Higher means a bumpier equity curve.",
    "bt.tip.maxDrawdown": "Largest fall from a peak to the lowest point after it — how much you would have been down at the worst moment.",
    "bt.tip.sharpe": "Return earned per unit of volatility (annualized, risk-free rate taken as 0). Higher is better.",
    "bt.tip.sortino": "Same as Sharpe, but only downside volatility counts as risk; upside swings are not penalized.",
    "bt.tip.omega": "Sum of all gains divided by sum of all losses. Above 1 means it made more than it lost.",
    "bt.tip.trades": "Number of position changes: each entry, exit, or resize counts once.",
    "bt.tip.winRate": "Share of days with a gain, among days that had any P&L. This is not a per-trade win rate.",
    "bt.tip.totalFees": "All fees paid over the period, as a percentage of capital.",
    "del.title": "Delete “{title}”?",
    "del.titleCur": "Delete this conversation?",
    "del.body": "This conversation’s chat history will be deleted and can’t be restored. Your strategies are not affected.",
    "del.bodyCur": "Its chat history will be deleted and can’t be restored. A new chat will open. Your strategies are not affected.",
    "del.cancel": "Cancel",
    "del.ok": "Delete",
    "chat.imageAlt": "Chart from the agent",
    "cn.signIn": "Sign in",
    "login.opened": "{name} sign-in is open in your browser. Come back here when you’re done.",
    "login.ok": "{name} is signed in.",
    "login.failed": "{name} sign-in didn’t finish.",
    "fault.localAuth": "{name} isn’t signed in, so this turn didn’t run.",
    "fault.localAuthBtn": "Sign In to {name}",
    "chat.imageZoom": "View larger",
    "login.cancel": "Cancel",
    "login.failedCmd": "Or run {cmd} in a terminal.",
    "login.retry": "Try Again",
    "fault.resend": "Send Again",
    "fault.resendDone": "Sent Again",
    "fault.authOk": "Blave is signed in again.",
    "cn.blave.signOut": "Sign out",
    "cn.blave.signOutLocalOnly": "Signed out on this computer, but the server couldn’t be reached to revoke this device. Revoke it under Settings › Devices on blave.org.",
    "acct.noCard": "Blave’s AI isn’t ready yet: this account has no card on file.",
    "acct.noCredit": "Blave’s AI isn’t ready yet: the balance is 0.",
    "acct.addCard": "Add a Card",
    "acct.sub": "A first card comes with {q} TWD of AI credit, plus Blave data in the desktop app for {t} days.",
    "acct.ready": "Ready to go.",
    "acct.creditIn": "Credit is in. You can send again.",
    "fault.needCard": "Blave’s AI needs a card on file, so this turn didn’t run.",
    "fault.checking": "This turn didn’t run — checking your account.",
    "set.cat.plan": "Data & cloud plan",
    "plan.st.running": "Active · machine running",
    "plan.st.stopped": "Stopped · balance under {m} TWD",
    "plan.st.stoppedNoAmt": "Stopped · balance too low",
    "plan.bill": "Billing",
    "plan.month": "{p} TWD / month",
    "plan.hour": "30 days = {h} TWD from your balance every hour",
    "plan.trialFree": "No machine fee until {d}. After that, the price above applies.",
    "plan.topup": "Under a balance of {a} TWD, your card is charged {b} TWD automatically. You can turn this off on the web.",
    "plan.start": "Start Plan",
    "plan.starting": "Starting…",
    "plan.addCredit": "Add Credit",
    "plan.addCard": "Add a Card",
    "plan.openWs": "Open Workspace",
    "plan.manage": "Turn off on the web",
    "plan.manageStopped": "Manage on the web",
    "cf.title": "Start the Blave Agent Cloud Plan?",
    "cf.body1": "This opens a cloud machine for this account, usually in about a minute. Blave data is available as soon as you start.",
    "cf.body2": "Once it’s up, {h} TWD comes out of your balance every hour ({p} TWD a month, 30 days), for as long as the machine exists, in use or not.",
    "cf.body2Trial": "No machine fee until {d}. After that, {h} TWD comes out of your balance every hour, for as long as the machine exists, in use or not.",
    "cf.body3": "To stop the charges, delete the machine on the web.",
    "cf.ok": "Start",
    "plan.err.credit": "Not started: the balance is too low.",
    "plan.err.nocard": "Not started: this account has no card on file.",
    "plan.err.relogin": "Sign in again before starting the plan. Your chats and strategies aren’t affected.",
    "plan.relogin": "Sign In Again",
    "plan.err.server": "The plan didn’t start. Pressing again won’t create a second machine.",
    "plan.err.rate": "Too many attempts. Try again in a while. A second machine won’t be created.",
    "plan.err.slow": "Taking longer than usual. The machine is still starting, so there’s no need to press again.",
    "plan.recheck": "Check Again",
    "data.starting": "Your cloud machine is starting. Blave data will be available in a moment.",
    "plan.done": "Your cloud machine is up.",
    "side.trial": "{n} days left",
    "side.starting": "Starting",
    "side.stopped": "Stopped",
    "data.ready": "Blave data is now available.",
    "pv.h.offer": "Your first card comes with {t} days of Blave data",
    "pv.h.offerNoNum": "Your first card comes with a trial period of Blave data",
    "pv.h.plan": "A cloud machine where strategies go live, Blave data included",
    "pv.h.ready": "Blave data is now available",
    "pv.h.starting": "Your cloud machine is starting. It usually takes about a minute",
    "pv.h.running": "Your strategies can now go live on the cloud machine",
    "pv.h.stopped": "The machine is stopped but still billing",
    "pv.h.unknown": "Couldn’t check this account",
    "pv.d.offer.cli": "AI stays on your {name}. When a strategy has to run around the clock, the cloud machine has no machine fee for those {t} days.",
    "pv.d.offer.blave": "Plus {q} TWD of AI credit. When a strategy has to run around the clock, the cloud machine has no machine fee for those {t} days.",
    "pv.d.noTrial": "The Blave Agent Cloud Plan, {p} TWD a month. This account has no first-card trial: add a card, then start the plan here to get data.",
    "pv.d.trial": "Until {d}, there’s no need to start the plan. After that, data comes with the Blave Agent Cloud Plan: {p} TWD a month.",
    "pv.d.plan": "The Blave Agent Cloud Plan, {p} TWD a month. Strategies run on schedule and place orders on this machine. The desktop app works without it, just without Blave data.",
    "pv.d.included": "You only need the Blave Agent Cloud Plan when a strategy has to run around the clock: {p} TWD a month.",
    "pv.d.starting": "Blave data is available right now, before the machine is up. You can close this window.",
    "pv.d.running": "Add strategies, set up scheduled reports and connect an exchange on this machine from the workspace. Strategies built on this computer stay on this computer.",
    "pv.d.stopped": "A stopped machine still bills {h} TWD an hour. At a balance of 0 the machine is deleted, along with the strategies and data on it.",
    "pv.d.noPrice": "Your AI setup stays as it is. After the trial, data comes with the Blave Agent Cloud Plan, if you start it.",
    "pv.d.unknown": "This may be a network problem. Checking again costs nothing.",
    "pv.f.out": "After {t} days, data comes with the cloud plan ({p} TWD a month), if you start it.",
    "pv.f.offer": "A {v} TWD card check goes to your balance, and auto top-up turns on. After {t} days, data comes with the cloud plan ({p} TWD a month), if you start it.",
    "pv.f.noTrial": "Adding the card tops up at least {b} TWD, all of it added to your balance, and turns on auto top-up.",
    "pv.f.trial": "When a strategy has to run around the clock, you can start now: no machine fee until {d}, then billed while the machine exists. Only deleting it ends the charges.",
    "pv.f.plan": "{h} TWD from your balance every hour, for as long as the machine exists. A stopped machine still bills. Only deleting it ends the charges.",
    "pv.f.running": "{h} TWD an hour from your balance ({p} TWD a month). Turning it off means deleting the machine on the web, with the strategies and data on it.",
    "pv.w.out.cli": "Signing in costs nothing and keeps your AI. Next: add a card.",
    "pv.w.noTrial": "Next: come back and start the plan.",
    "pv.w.waiting": "Your browser is open. Press Allow there.",
    "pv.st.trial": "Trial · {n} days left",
    "pv.st.none": "Not started",
    "pv.st.ok": "Available",
    "pv.st.starting": "Starting",
    "pv.more": "What’s included and billing",
    "plan.inc": "Included",
    "plan.rule": "Billed for as long as the machine exists, in use or not. A stopped machine still bills. Only deleting it ends the charges.",
    "plan.rule.running": "Billed for as long as the machine exists, in use or not. Turning the plan off means deleting the machine, along with the strategies and data on it.",
    "pv.more.once": "The first-card trial is once per person and once per card.",
    "pv.inc.1": "A cloud machine that stays on 24 hours: strategies run on schedule and place orders",
    "pv.inc.2": "Blave data, in the desktop app and on the cloud machine",
    "pv.inc.3": "Operate the machine from the browser workspace",
    "pv.inc.note": "Strategies built on this computer stay on this computer. Strategies on the machine are built in the workspace, where exchange keys are connected too.",
    "pv.signin": "Sign in to Blave",
    "pv.e.out": "This computer can’t reach Blave data yet. Sign in to Blave, and your first card comes with {t} days of it. AI stays on your {name}.",
    "pv.e.outNoNum": "This computer can’t reach Blave data yet. Sign in to Blave, and your first card comes with a trial period of it. AI stays on your {name}.",
    "pv.e.card": "This computer can’t reach Blave data yet. Your first card comes with {t} days of it.",
    "pv.e.card.cli": "This computer can’t reach Blave data yet. Your first card comes with {t} days of it. AI stays on your {name}.",
    "pv.e.noTrial": "This computer can’t reach Blave data yet. It comes with the Blave Agent Cloud Plan.",
    "pv.e.sub": "After that, data comes with the Blave Agent Cloud Plan at {p} TWD a month.",
    "pv.e.subN": "{p} TWD a month: a cloud machine where strategies run around the clock, Blave data included. Billed hourly for as long as the machine exists.",
    "pv.e.unknown": "This computer can’t reach Blave data yet. The account status couldn’t be checked. Open Data & Cloud Plan to check again.",
    "pv.e.btn": "Data & Cloud Plan",
    "cn.blave.signinSwitch": "Sign In and Switch",
    "cn.foot.data": "Your first card comes with {t} days of Blave data, whichever AI you use: after connecting, see Settings › Data & cloud plan.",
    "acct.lbl": "Blave account",
    "acct.signedIn": "Signed in",
    "acct.out": "Sign out",
    "acct.outDone": "Signed out. This computer no longer gets Blave data.",
  },
  zh: {
    "cn.h": "Blave 不內建 AI。",
    "cn.blave.title": "用 Blave 的 AI",
    "cn.blave.desc": "首次綁卡送 100 TWD 的 AI 額度，之後按用量計費",
    "cn.blave.btn": "登入 Blave",
    "cn.blave.switch": "切換",
    "cn.local.label": "本機 agent",
    "cn.local.desc": "你的 Claude Code 或 Codex，Blave 不收 AI 費用",
    "cn.redetect": "重新偵測",
    "cn.detecting": "偵測中…",
    "cn.connect": "連結",
    "cn.foot": "連結後可以隨時更換。",
    "st.signedIn": "已登入",
    "st.notSignedIn": "尚未登入",
    "st.notFound": "未偵測到",
    "oauth.waiting": "等待瀏覽器授權…",
    "oauth.cancel": "取消等待",
    "oauth.opened": "已在瀏覽器開啟授權頁，完成後會自動回到這裡。",
    "oauth.failed": "授權失敗。",
    "OAUTH_CANCELLED": "已取消。要用 Blave 的 AI 再按一次。",
    "OAUTH_TIMEOUT": "授權逾時（5 分鐘）。",
    "OAUTH_STATE_MISMATCH": "回來的授權跟這次請求對不上，已擋下。",
    "OAUTH_NO_CODE": "瀏覽器回來了，但沒有帶授權碼。",
    "OAUTH_DENIED": "你在瀏覽器取消了授權。",
    "KEYCHAIN_UNAVAILABLE": "這台電腦無法安全儲存憑證（Keychain 不可用），沒有保存。",
    "TOKEN_EXCHANGE_FAILED": "授權碼換不到 token。",
    "ws.chatExample": "回測一支 BTC 20/50 均線策略",
    "ws.strategies": "策略",
    "ws.noStrategies": "還沒有策略。",
    "ws.placeholder": "跟 agent 說一句話",
    "ws.send": "送出",
    "ws.settings": "設定",
    "turn.process": "思考過程",
    "turn.thinking": "思考中",
    "turn.running": "執行中 · 第 {n} 步",
    "turn.busy": "上一輪還在跑。",
    "turn.engineFailed": "引擎準備失敗：{msg}",
    "turn.exit": "引擎退出碼 {code}",
    "turn.error": "出錯了：{msg}",
    "fault.authInvalid": "這台電腦的 Blave 登入已失效，這一輪沒有跑。",
    "fault.authBtn": "重新登入 Blave",
    "fault.noCredit": "Blave 餘額用完了，這一輪沒有跑。",
    "fault.noCreditBtn": "儲值",
    "conn.expired": "Blave 登入已失效，重新登入後繼續。",
    "engine.workspace": "建立工作區 ~/Blave/workspace …",
    "engine.deps": "正在安裝策略需要的 Python 套件（pandas、numpy…），只有第一次…",
    "engine.preparing": "正在準備引擎（第一次會安裝，約一分鐘）…",
    "mp.model": "模型",
    "mp.effort": "思考深度",
    "mp.default": "預設",
    "mp.aria": "模型與思考深度：{model}，{effort}",
    "mp.ariaNoEffort": "模型：{model}",
    "mp.cap": "{model} 的預設是「{level}」。越高想得越久、用得越多。",
    "mp.none": "這個模型沒有思考深度可調。",
    "lv.low": "低",
    "lv.medium": "中",
    "lv.high": "高",
    "lv.xhigh": "超高",
    "lv.max": "最高",
    "lv.ultra": "Ultra",
    "fault.noModel": "你的帳號用不了「{model}」，這一輪沒有跑。",
    "fault.noModelSwitched": "你的帳號用不了「{model}」，這一輪沒有跑。已換回「{to}」。",
    "fault.noModelBtn": "選別的模型",
    "mp.na": "你的方案沒有",
    "rp.tab.backtest": "回測數據",
    "rp.tab.trades": "進出場紀錄",
    "rp.tab.code": "程式碼",
    "bt.fee": "手續費",
    "bt.totalReturn": "總報酬",
    "bt.benchmark": "基準報酬",
    "bt.benchmarkRank": "贏過 {n}% 隨機投組",
    "bt.sharpe": "Sharpe",
    "bt.maxDrawdown": "最大回撤",
    "bt.trades": "交易次數",
    "bt.mcpt": "MCPT p 值",
    "bt.mcptTipSig": "隨機打亂 {n} 次，只有 {pct} 的結果比它好；低於 0.05 是慣用門檻。",
    "bt.mcptTipNs": "隨機打亂 {n} 次，有 {pct} 的結果比它好——沒過 0.05 的慣用門檻，這組結果分不出是實力還是運氣。",
    "bt.equity": "權益",
    "bt.drawdown": "回撤",
    "bt.chartAria": "回測期間的權益曲線與回撤",
    "bt.monthly": "月報酬",
    "bt.year": "全年",
    "bt.empty": "這支策略沒有回測資料。",
    "tr.empty": "這支策略沒有進出場紀錄。",
    "tr.chartError": "圖表畫不出來，下方的進出場紀錄仍可查看。",
    "tr.list": "進出場紀錄",
    "tr.count": "{n} 筆",
    "tr.buy": "買進",
    "tr.sell": "賣出",
    "tr.kind.open": "開倉",
    "tr.kind.close": "平倉",
    "tr.kind.flip": "翻向",
    "tr.position": "部位 {n}",
    "bt.grpReturns": "報酬",
    "bt.grpRisk": "風險",
    "bt.grpTrading": "交易",
    "bt.annReturn": "年化報酬",
    "bt.annVol": "年化波動率",
    "bt.sortino": "Sortino",
    "bt.omega": "Omega",
    "bt.winRate": "日勝率",
    "bt.totalFees": "總手續費",
    "bt.mcptDistTitle": "MCPT · 隨機打亂 {n} 次的 Sharpe 分佈，p = {p}",
    "bt.mcptDistActual": "實際 Sharpe {v}",
    "bt.mcptDistUnit": "次",
    "ws.resizeSide": "調整策略欄寬度",
    "ws.resizeChat": "調整聊天欄寬度",
    "ws.sideCollapse": "收合策略欄",
    "ws.sideExpand": "展開策略欄",
    "ws.chatCollapse": "收合聊天欄",
    "ws.chatExpand": "展開聊天欄",
    "set.close": "關閉",
    "set.cats": "設定分類",
    "set.cat.display": "顯示",
    "set.cat.model": "模型接入",
    "set.lang": "語言",
    "cn.current": "使用中",
    "cs.all": "所有對話",
    "cs.back": "返回對話",
    "cs.new": "新對話",
    "cs.del": "刪除對話",
    "cs.delConfirm": "刪除？",
    "strat.del": "移到垃圾桶",
    "bt.tip.totalReturn": "整段回測期間的累計報酬，已扣手續費。",
    "bt.tip.annReturn": "把總報酬換算成一年的複利報酬，方便跟不同長度的回測比較。",
    "bt.tip.benchmark": "同一段期間買進後一直持有這個標的的報酬。策略要贏過它，才算比什麼都不做好。",
    "bt.tip.benchmarkRank": "跟隨機挑標的、買進持有的投組比，這支策略的總報酬贏過其中多少。",
    "bt.tip.annVol": "每日報酬的標準差換算成一年。數字越大，權益的起伏越劇烈。",
    "bt.tip.maxDrawdown": "權益從高點跌到之後最低點的最大跌幅，也就是最壞的時候帳面會少掉多少。",
    "bt.tip.sharpe": "每承擔一單位波動換到多少報酬（年化，無風險利率以 0 計）。越高越好。",
    "bt.tip.sortino": "算法同 Sharpe，但只把下跌的波動當成風險，上漲的波動不扣分。",
    "bt.tip.omega": "所有賺錢時段的報酬總和，除以所有虧錢時段的虧損總和。大於 1 表示賺的比賠的多。",
    "bt.tip.trades": "部位有變動的次數：進場、出場、加減碼各算一次。",
    "bt.tip.winRate": "有損益的日子裡，賺錢的日子佔多少。這不是每筆交易的勝率。",
    "bt.tip.totalFees": "整段期間付出的手續費加總，以佔資金的百分比表示。",
    "del.title": "刪除「{title}」？",
    "del.titleCur": "刪除目前這個對話？",
    "del.body": "這條對話的聊天記錄會刪除，無法復原。策略不受影響。",
    "del.bodyCur": "聊天記錄會刪除，無法復原。刪除後會開一條新對話。策略不受影響。",
    "del.cancel": "取消",
    "del.ok": "刪除",
    "chat.imageAlt": "agent 傳來的圖",
    "cn.signIn": "登入",
    "login.opened": "已在瀏覽器開啟 {name} 登入頁，完成後回到這裡。",
    "login.ok": "{name} 已登入。",
    "login.failed": "{name} 登入沒有完成。",
    "fault.localAuth": "{name} 目前沒有登入，這一輪沒有跑。",
    "fault.localAuthBtn": "登入 {name}",
    "chat.imageZoom": "放大檢視",
    "login.cancel": "取消等待",
    "login.failedCmd": "也可以在終端機執行 {cmd}。",
    "login.retry": "再試一次",
    "fault.resend": "再送一次",
    "fault.resendDone": "已重新送出",
    "fault.authOk": "Blave 已重新登入。",
    "cn.blave.signOut": "登出",
    "cn.blave.signOutLocalOnly": "這台電腦已登出，但連不上伺服器、沒能撤銷這台裝置的授權。到 blave.org 的設定 › 裝置再撤銷一次。",
    "acct.noCard": "Blave 的 AI 還不能用：這個帳號還沒綁卡。",
    "acct.noCredit": "Blave 的 AI 還不能用：餘額是 0。",
    "acct.addCard": "前往綁卡",
    "acct.sub": "首次綁卡有 {q} TWD 的 AI 額度，{t} 天內電腦版也拿得到 Blave 的資料。",
    "acct.ready": "可以開始了。",
    "acct.creditIn": "額度到了，可以再送了。",
    "fault.needCard": "用 Blave 的 AI 要先綁卡，這一輪沒有跑。",
    "fault.checking": "這一輪沒有跑，正在確認帳號狀態。",
    "set.cat.plan": "資料與雲端方案",
    "plan.st.running": "已啟動 · 主機運行中",
    "plan.st.stopped": "已停機 · 餘額低於 {m} TWD",
    "plan.st.stoppedNoAmt": "已停機 · 餘額不足",
    "plan.bill": "計費",
    "plan.month": "{p} TWD／月",
    "plan.hour": "以 30 天計 ＝ 每個整點從餘額扣 {h} TWD",
    "plan.trialFree": "{d}前免主機費，之後照上面的價格。",
    "plan.topup": "餘額低於 {a} TWD 時，會從綁定的卡自動儲值 {b} TWD；可以在網頁關閉。",
    "plan.start": "啟動方案",
    "plan.starting": "啟動中…",
    "plan.addCredit": "前往儲值",
    "plan.addCard": "前往綁卡",
    "plan.openWs": "前往工作頁",
    "plan.manage": "前往網頁停用",
    "plan.manageStopped": "前往網頁管理",
    "cf.title": "啟動 Blave Agent 雲端方案？",
    "cf.body1": "會替這個帳號開一台雲端主機，通常 1 分鐘左右。Blave 的資料一啟動就能用。",
    "cf.body2": "開好後每個整點從餘額扣 {h} TWD（每月 {p} TWD，以 30 天計）；主機存在就會扣，不管有沒有在用。",
    "cf.body2Trial": "{d}前免主機費；之後每個整點從餘額扣 {h} TWD，主機存在就會扣，不管有沒有在用。",
    "cf.body3": "要停止收費，需到網頁刪除主機。",
    "cf.ok": "啟動",
    "plan.err.credit": "餘額不足，沒有啟動。",
    "plan.err.nocard": "這個帳號還沒綁卡，沒有啟動。",
    "plan.err.relogin": "啟動方案前要重新登入一次。聊天與策略不受影響。",
    "plan.relogin": "重新登入",
    "plan.err.server": "啟動沒有完成。再按一次不會重複開主機。",
    "plan.err.rate": "按得太頻繁了，請過一陣子再試。不會重複開主機。",
    "plan.err.slow": "比平常久。主機還在啟動，不需要再按一次。",
    "plan.recheck": "重新查看",
    "data.starting": "雲端主機啟動中；Blave 的資料馬上就能用。",
    "plan.done": "雲端主機開好了。",
    "side.trial": "試用剩 {n} 天",
    "side.starting": "啟動中",
    "side.stopped": "已停機",
    "data.ready": "Blave 的資料可以用了。",
    "pv.h.offer": "首次綁卡，送 {t} 天 Blave 的資料",
    "pv.h.offerNoNum": "首次綁卡，送一段試用期的 Blave 資料",
    "pv.h.plan": "策略上線的雲端主機，含 Blave 的資料",
    "pv.h.ready": "Blave 的資料可以用了",
    "pv.h.starting": "雲端主機啟動中，通常 1 分鐘左右",
    "pv.h.running": "策略可以在雲端主機上線了",
    "pv.h.stopped": "主機停機了，但還在扣款",
    "pv.h.unknown": "查不到這個帳號的狀態",
    "pv.d.offer.cli": "AI 照用你的 {name}。想讓策略全天候自動執行，這 {t} 天開雲端主機也免主機費。",
    "pv.d.offer.blave": "另有 {q} TWD 的 AI 額度。想讓策略全天候自動執行，這 {t} 天開雲端主機也免主機費。",
    "pv.d.noTrial": "Blave Agent 雲端方案：{p} TWD／月。這個帳號沒有首次綁卡的試用，綁卡後要回來啟動方案才有資料。",
    "pv.d.trial": "到 {d}為止，不用啟動方案。之後，資料在 Blave Agent 雲端方案裡：{p} TWD／月。",
    "pv.d.plan": "Blave Agent 雲端方案：{p} TWD／月。策略在這台主機上照排程執行、自動下單；電腦版不啟動也能用，只是沒有 Blave 的資料。",
    "pv.d.included": "想讓策略全天候自動執行，才需要啟動 Blave Agent 雲端方案：{p} TWD／月。",
    "pv.d.starting": "Blave 的資料現在就能用，不用等主機開好。可以關掉這個視窗。",
    "pv.d.running": "到工作頁在這台主機上新增策略、設定定期報告、連接交易所。電腦上做的策略留在電腦上，兩邊各是一份。",
    "pv.d.stopped": "停機期間仍每小時扣 {h} TWD。餘額歸零時主機會刪除，主機上的策略與資料一併清除。",
    "pv.d.noPrice": "AI 照用你現在的設定。試用結束後要資料，再啟動 Blave Agent 雲端方案。",
    "pv.d.unknown": "可能是網路問題。重新查看不會花錢。",
    "pv.f.out": "{t} 天後要資料，再啟動雲端方案（{p} TWD／月）。",
    "pv.f.offer": "綁卡時收 {v} TWD 驗證金，全額進你的餘額，並開啟自動儲值。{t} 天後要資料，再啟動雲端方案（{p} TWD／月）。",
    "pv.f.noTrial": "綁卡時最少儲值 {b} TWD，全額進你的餘額，並開啟自動儲值。",
    "pv.f.trial": "想讓策略全天候自動執行，現在就能啟動：{d}前免主機費，之後主機存在就扣，刪除才停。",
    "pv.f.plan": "每個整點從餘額扣 {h} TWD。主機存在就扣，停機照扣，刪除才停。",
    "pv.f.running": "每個整點從餘額扣 {h} TWD（{p} TWD／月）。停用＝到網頁刪除主機，主機上的策略與資料一併清除。",
    "pv.w.out.cli": "登入不花錢，也不改你用的 AI。下一步是綁卡。",
    "pv.w.noTrial": "下一步：回來啟動方案。",
    "pv.w.waiting": "瀏覽器已開啟，請在那邊按「允許」。",
    "pv.st.trial": "試用中 · 剩 {n} 天",
    "pv.st.none": "未啟動",
    "pv.st.ok": "可用",
    "pv.st.starting": "啟動中",
    "pv.more": "方案內容與計費",
    "plan.inc": "內含",
    "plan.rule": "主機存在就會扣，不管有沒有在用；停機照扣，刪除主機才停。",
    "plan.rule.running": "主機存在就會扣，不管有沒有在用。停用＝刪除主機，主機上的策略與資料會一併清除。",
    "pv.more.once": "首次綁卡的試用每人一次、每張卡一次。",
    "pv.inc.1": "一台 24 小時開著的雲端主機：策略照排程執行、自動下單",
    "pv.inc.2": "Blave 的資料，電腦版與雲端主機都拿得到",
    "pv.inc.3": "從瀏覽器的工作頁操作這台主機",
    "pv.inc.note": "電腦上做的策略留在電腦上。主機上的策略在工作頁建立，交易所金鑰也在那邊綁。",
    "pv.signin": "登入 Blave",
    "pv.e.out": "這台還拿不到 Blave 的資料。登入 Blave 後首次綁卡，送 {t} 天；AI 照用你的 {name}。",
    "pv.e.outNoNum": "這台還拿不到 Blave 的資料。登入 Blave 後首次綁卡，送一段試用期；AI 照用你的 {name}。",
    "pv.e.card": "這台還拿不到 Blave 的資料。首次綁卡，送 {t} 天。",
    "pv.e.card.cli": "這台還拿不到 Blave 的資料。首次綁卡，送 {t} 天；AI 照用你的 {name}。",
    "pv.e.noTrial": "這台還拿不到 Blave 的資料：它在 Blave Agent 雲端方案裡。",
    "pv.e.sub": "之後資料在每月 {p} TWD 的 Blave Agent 雲端方案裡。",
    "pv.e.subN": "每月 {p} TWD：一台讓策略全天候自動執行的雲端主機，含 Blave 的資料；主機存在就按小時扣。",
    "pv.e.unknown": "這台還拿不到 Blave 的資料。現在查不到帳號狀態，到「資料與雲端方案」重新查看。",
    "pv.e.btn": "資料與雲端方案",
    "cn.blave.signinSwitch": "登入並切換",
    "cn.foot.data": "首次綁卡送 {t} 天 Blave 的資料，用哪一種 AI 都拿得到：連結後到設定 › 資料與雲端方案。",
    "acct.lbl": "Blave 帳號",
    "acct.signedIn": "已登入",
    "acct.out": "登出",
    "acct.outDone": "已登出。這台不再拿得到 Blave 的資料。",
  },
};
